    SCENE_CMD_ALTERNATE_HEADER_LIST(yousei_izumi_yoko_scene_02000060_AltHeaders),
    SCENE_CMD_SOUND_SETTINGS(9, NATURE_ID_NONE, NA_BGM_GREAT_FAIRY),
    SCENE_CMD_ROOM_LIST(ARRAY_COUNT(yousei_izumi_yoko_scene_020000A8_RoomList), yousei_izumi_yoko_scene_020000A8_RoomList),
    SCENE_CMD_MISC_SETTINGS(SCENE_CAM_TYPE_DEFAULT, WORLD_MAP_AREA_MAX),
    SCENE_CMD_COL_HEADER(&yousei_izumi_yoko_scene_020039A8_Col),
    SCENE_CMD_SPAWN_LIST(yousei_izumi_yoko_scene_020000B0_SpawnList),
    SCENE_CMD_SPECIAL_FILES(NAVI_QUEST_HINTS_OVERWORLD, OBJECT_GAMEPLAY_FIELD_KEEP),
    SCENE_CMD_PLAYER_ENTRY_LIST(ARRAY_COUNT(yousei_izumi_yoko_scene_02000078_PlayerEntryList), yousei_izumi_yoko_scene_02000078_PlayerEntryList),
    SCENE_CMD_SKYBOX_SETTINGS(SKYBOX_NONE, 0, LIGHT_MODE_SETTINGS),
    SCENE_CMD_EXIT_LIST(yousei_izumi_yoko_scene_020000B8_ExitList),
    SCENE_CMD_ENV_LIGHT_SETTINGS(ARRAY_COUNT(yousei_izumi_yoko_scene_020000BC_EnvLightSettingsList), yousei_izumi_yoko_scene_020000BC_EnvLightSettingsList),
    SCENE_CMD_END(),
