#ifndef Z_BEAST_H
#define Z_BEAST_H

#include "animation.h"
#include "ultra64.h"

extern u64 gBeastSkel_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_ci4[];
extern u64 gBeastSkel_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_pal_rgba16[];
extern u64 gBeastSkel_furcutout_ia8[];
extern u64 gBeastSkel_uppermouth_i4[];
extern u64 gBeastSkel_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4[];
extern u64 gBeastSkel_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16[];
extern u64 gBeastSkel_dogmouth_i4[];
extern Vtx gBeastSkel_Chest_mesh_layer_Opaque_vtx_0[49];
extern Gfx gBeastSkel_Chest_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Chest_mesh_layer_Opaque_vtx_1[26];
extern Gfx gBeastSkel_Chest_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Head_mesh_layer_Opaque_vtx_0[130];
extern Gfx gBeastSkel_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Head_mesh_layer_Opaque_vtx_1[5];
extern Gfx gBeastSkel_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Head_mesh_layer_Opaque_vtx_2[16];
extern Gfx gBeastSkel_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gBeastSkel_Head_mesh_layer_Opaque_vtx_3[18];
extern Gfx gBeastSkel_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gBeastSkel_Jaw_mesh_layer_Opaque_vtx_0[38];
extern Gfx gBeastSkel_Jaw_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Jaw_mesh_layer_Opaque_vtx_1[9];
extern Gfx gBeastSkel_Jaw_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Jaw_mesh_layer_Opaque_vtx_2[10];
extern Gfx gBeastSkel_Jaw_mesh_layer_Opaque_tri_2[];
extern Vtx gBeastSkel_Shoulder_L_mesh_layer_Opaque_vtx_0[47];
extern Gfx gBeastSkel_Shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Arm_L_mesh_layer_Opaque_vtx_0[17];
extern Gfx gBeastSkel_Arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Hand_L_mesh_layer_Opaque_vtx_0[32];
extern Gfx gBeastSkel_Hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Claw_L_mesh_layer_Opaque_vtx_0[45];
extern Gfx gBeastSkel_Claw_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Claw_L_mesh_layer_Opaque_vtx_1[36];
extern Gfx gBeastSkel_Claw_L_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Shoulder_R_mesh_layer_Opaque_vtx_0[47];
extern Gfx gBeastSkel_Shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Arm_R_mesh_layer_Opaque_vtx_0[17];
extern Gfx gBeastSkel_Arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Hand_R_mesh_layer_Opaque_vtx_0[32];
extern Gfx gBeastSkel_Hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Claw_R_mesh_layer_Opaque_vtx_0[45];
extern Gfx gBeastSkel_Claw_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Claw_R_mesh_layer_Opaque_vtx_1[36];
extern Gfx gBeastSkel_Claw_R_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Hip_mesh_layer_Opaque_vtx_0[41];
extern Gfx gBeastSkel_Hip_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Hip_mesh_layer_Opaque_vtx_1[16];
extern Gfx gBeastSkel_Hip_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Leg_L_mesh_layer_Opaque_vtx_0[23];
extern Gfx gBeastSkel_Leg_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Shin_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gBeastSkel_Shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Foot_L_mesh_layer_Opaque_vtx_0[28];
extern Gfx gBeastSkel_Foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_FClaw_L_mesh_layer_Opaque_vtx_0[73];
extern Gfx gBeastSkel_FClaw_L_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_FClaw_L_mesh_layer_Opaque_vtx_1[35];
extern Gfx gBeastSkel_FClaw_L_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Leg_R_mesh_layer_Opaque_vtx_0[23];
extern Gfx gBeastSkel_Leg_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Shin_R_mesh_layer_Opaque_vtx_0[24];
extern Gfx gBeastSkel_Shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_Foot_R_mesh_layer_Opaque_vtx_0[28];
extern Gfx gBeastSkel_Foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_FClaw_R_mesh_layer_Opaque_vtx_0[79];
extern Gfx gBeastSkel_FClaw_R_mesh_layer_Opaque_tri_0[];
extern Vtx gBeastSkel_FClaw_R_mesh_layer_Opaque_vtx_1[36];
extern Gfx gBeastSkel_FClaw_R_mesh_layer_Opaque_tri_1[];
extern Vtx gBeastSkel_Tail_mesh_layer_Opaque_vtx_0[8];
extern Gfx gBeastSkel_Tail_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gBeastSkel_f3dlite_material_004_layerOpaque[];
extern Gfx mat_gBeastSkel_f3dlite_material_008_layerOpaque[];
extern Gfx mat_gBeastSkel_f3dlite_material_007_layerOpaque[];
extern Gfx mat_gBeastSkel_f3dlite_material_005_layerOpaque[];
extern Gfx mat_gBeastSkel_f3dlite_material_006_layerOpaque[];
extern Gfx mat_gBeastSkel_f3dlite_material_layerOpaque[];
extern Gfx gBeastSkel_Chest_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Head_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Jaw_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Shoulder_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Arm_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Hand_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Claw_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Shoulder_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Arm_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Hand_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Claw_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Hip_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Leg_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Shin_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Foot_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_FClaw_L_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Leg_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Shin_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Foot_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_FClaw_R_mesh_layer_Opaque[];
extern Gfx gBeastSkel_Tail_mesh_layer_Opaque[];
extern FlexSkeletonHeader gBeastSkel;
#define GBEASTSKEL_ROOT_POS_LIMB 0
#define GBEASTSKEL_ROOT_ROT_LIMB 1
#define GBEASTSKEL_CHEST_LIMB 2
#define GBEASTSKEL_HEAD_LIMB 3
#define GBEASTSKEL_JAW_LIMB 4
#define GBEASTSKEL_SHOULDER_L_LIMB 5
#define GBEASTSKEL_ARM_L_LIMB 6
#define GBEASTSKEL_HAND_L_LIMB 7
#define GBEASTSKEL_CLAW_L_LIMB 8
#define GBEASTSKEL_SHOULDER_R_LIMB 9
#define GBEASTSKEL_ARM_R_LIMB 10
#define GBEASTSKEL_HAND_R_LIMB 11
#define GBEASTSKEL_CLAW_R_LIMB 12
#define GBEASTSKEL_HIP_LIMB 13
#define GBEASTSKEL_LEG_L_LIMB 14
#define GBEASTSKEL_SHIN_L_LIMB 15
#define GBEASTSKEL_FOOT_L_LIMB 16
#define GBEASTSKEL_FCLAW_L_LIMB 17
#define GBEASTSKEL_LEG_R_LIMB 18
#define GBEASTSKEL_SHIN_R_LIMB 19
#define GBEASTSKEL_FOOT_R_LIMB 20
#define GBEASTSKEL_FCLAW_R_LIMB 21
#define GBEASTSKEL_TAIL_LIMB 22
#define GBEASTSKEL_NUM_LIMBS 23

extern AnimationHeader gBeastSkelAttackaAnim;
extern AnimationHeader gBeastSkelAttackbAnim;
extern AnimationHeader gBeastSkelAttackcAnim;
extern AnimationHeader gBeastSkelAttackdAnim;
extern AnimationHeader gBeastSkelBackjumpAnim;
extern AnimationHeader gBeastSkelDeathAnim;
extern AnimationHeader gBeastSkelIdleAnim;
extern AnimationHeader gBeastSkelIdle2Anim;
extern AnimationHeader gBeastSkelStaggerAnim;
extern AnimationHeader gBeastSkelWalkaAnim;
extern AnimationHeader gBeastSkelAttackdaAnim;
extern AnimationHeader gBeastSkelAttackdbAnim;
extern AnimationHeader gBeastSkelAttackdcAnim;

#endif
