    OBJECT_MENKURI_OBJECTS, // 0
    OBJECT_BOX, // 1
    OBJECT_EFC_FLASH, // 2
    OBJECT_TIMEBLOCK, // 3
    OBJECT_EFC_TW, // 4
    OBJECT_SYOKUDAI, // 5
    OBJECT_SK2, // 6
    OBJECT_ST, // 7
    OBJECT_ICE_OBJECTS, // 8

