    SCENE_CMD_QUEST_HEADER_LIST(questHeaders),
    SCENE_CMD_ECHO_SETTINGS(4),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_DUNGEON, ROOM_ENV_HOT, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(true /* no skybox */, true /* no sun/moon */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 0 /* time doesn't move */),
    SCENE_CMD_ROOM_SHAPE(&HIDAN_room_16_03000100_RoomShapeCullable),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(HIDAN_room_16_03000040_ObjectList), HIDAN_room_16_03000040_ObjectList),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(HIDAN_room_16_03000054_ActorEntryList), HIDAN_room_16_03000054_ActorEntryList),
    SCENE_CMD_END(),
