    OBJECT_HAKA_OBJECTS, // 0
    OBJECT_HAKA_DOOR, // 1
    OBJECT_GI_KEY, // 2
    OBJECT_GI_BOMB_1, // 3
    OBJECT_GI_MAGICPOT, // 4
    OBJECT_GI_ARROW, // 5
    OBJECT_FIREFLY, // 6
    OBJECT_ST, // 7
    OBJECT_GI_SOUL, // 8
    OBJECT_BOMBF, // 9

