    OBJECT_HAKA_OBJECTS, // 0
    OBJECT_HAKA_DOOR, // 1
    OBJECT_BOX, // 2
    OBJECT_VM, // 3
    OBJECT_KANBAN, // 4
    OBJECT_ST, // 5
    OBJECT_BB, // 6
    OBJECT_POH, // 7
    OBJECT_TRAP, // 8

