#ifndef OBJECT_MINIBLIN_H
#define OBJECT_MINIBLIN_H 1

#include "animation.h"
#include "ultra64.h"

extern AnimationHeader gMiniblinSkelIdleAnim;
extern AnimationHeader gMiniblinSkelJumpAnim;
extern AnimationHeader gMiniblinSkelTailattackAnim;
extern AnimationHeader gMiniblinSkelDeathAnim;
extern AnimationHeader gMiniblinSkelDamageAnim;
extern AnimationHeader gMiniblinSkelLaughAnim;
extern AnimationHeader gMiniblinSkelBombthrowAnim;

extern u64 gMiniblinSkel_miniblin_body_ci8[];
extern u64 gMiniblinSkel_miniblin_body_pal_rgba16[];
extern u64 gMiniblinSkel_miniblin_eye_ci8[];
extern u64 gMiniblinSkel_miniblin_eye_pal_rgba16[];
extern u64 gMiniblinSkel_teeth_ci8[];
extern u64 gMiniblinSkel_teeth_pal_rgba16[];
extern u64 gMiniblinSkel_eye_normal_rgba16[];
extern u64 gMiniblinSkel_eye_halfclosed_rgba16[];
extern u64 gMiniblinSkel_eye_closed_rgba16[];
extern u64 gMiniblinSkel_eye_laugh_rgba16[];
extern u64 gMiniblinSkel_eye_hit_rgba16[];
extern u64 gMiniblinSkel_miniblin_foot_ci4[];
extern u64 gMiniblinSkel_miniblin_foot_pal_rgba16[];
extern u64 gMiniblinSkel_miniblin_ear_ci8[];
extern u64 gMiniblinSkel_miniblin_ear_pal_rgba16[];
extern u64 gMiniblinSkel_miniblin_hand_ci8[];
extern u64 gMiniblinSkel_miniblin_hand_pal_rgba16[];
extern Vtx gMiniblinSkel_body_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMiniblinSkel_body_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_head_mesh_layer_Opaque_vtx_0[54];
extern Gfx gMiniblinSkel_head_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_head_mesh_layer_Opaque_vtx_1[13];
extern Gfx gMiniblinSkel_head_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_head_mesh_layer_Opaque_vtx_2[8];
extern Gfx gMiniblinSkel_head_mesh_layer_Opaque_tri_2[];
extern Vtx gMiniblinSkel_head_mesh_layer_Opaque_vtx_3[8];
extern Gfx gMiniblinSkel_head_mesh_layer_Opaque_tri_3[];
extern Vtx gMiniblinSkel_head_mesh_layer_Opaque_vtx_4[30];
extern Gfx gMiniblinSkel_head_mesh_layer_Opaque_tri_4[];
extern Vtx gMiniblinSkel_leftear1_mesh_layer_Opaque_vtx_0[17];
extern Gfx gMiniblinSkel_leftear1_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_leftear1_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMiniblinSkel_leftear1_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_leftear2_mesh_layer_Opaque_vtx_0[4];
extern Gfx gMiniblinSkel_leftear2_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_leftear2_mesh_layer_Opaque_vtx_1[6];
extern Gfx gMiniblinSkel_leftear2_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_rightear1_mesh_layer_Opaque_vtx_0[21];
extern Gfx gMiniblinSkel_rightear1_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_rightear1_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMiniblinSkel_rightear1_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_rightear2_mesh_layer_Opaque_vtx_0[5];
extern Gfx gMiniblinSkel_rightear2_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_rightear2_mesh_layer_Opaque_vtx_1[4];
extern Gfx gMiniblinSkel_rightear2_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_hip_l_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_hip_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_upperleg_l_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_upperleg_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_leg_l_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_leg_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_foot_l_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_foot_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_foot_l_mesh_layer_Opaque_vtx_1[22];
extern Gfx gMiniblinSkel_foot_l_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_hip_r_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_hip_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_upperleg_r_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_upperleg_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_leg_r_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_leg_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_foot_r_mesh_layer_Opaque_vtx_0[8];
extern Gfx gMiniblinSkel_foot_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_foot_r_mesh_layer_Opaque_vtx_1[32];
extern Gfx gMiniblinSkel_foot_r_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_tail1_mesh_layer_Opaque_vtx_0[15];
extern Gfx gMiniblinSkel_tail1_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_tailend_mesh_layer_Opaque_vtx_0[14];
extern Gfx gMiniblinSkel_tailend_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_mouth_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMiniblinSkel_mouth_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_mouth_mesh_layer_Opaque_vtx_1[6];
extern Gfx gMiniblinSkel_mouth_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_shoulder_l_mesh_layer_Opaque_vtx_0[18];
extern Gfx gMiniblinSkel_shoulder_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_upperarm_l_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMiniblinSkel_upperarm_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_arm_l_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMiniblinSkel_arm_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_hand_l_mesh_layer_Opaque_vtx_0[43];
extern Gfx gMiniblinSkel_hand_l_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_hand_l_mesh_layer_Opaque_vtx_1[6];
extern Gfx gMiniblinSkel_hand_l_mesh_layer_Opaque_tri_1[];
extern Vtx gMiniblinSkel_shoulder_r_mesh_layer_Opaque_vtx_0[15];
extern Gfx gMiniblinSkel_shoulder_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_upperarm_r_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMiniblinSkel_upperarm_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_arm_r_mesh_layer_Opaque_vtx_0[12];
extern Gfx gMiniblinSkel_arm_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_hand_r_mesh_layer_Opaque_vtx_0[6];
extern Gfx gMiniblinSkel_hand_r_mesh_layer_Opaque_tri_0[];
extern Vtx gMiniblinSkel_hand_r_mesh_layer_Opaque_vtx_1[39];
extern Gfx gMiniblinSkel_hand_r_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_007_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_162_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_160_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_159_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_164_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_158_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_163_layerOpaque[];
extern Gfx mat_gMiniblinSkel_f3dlite_material_157_layerOpaque[];
extern Gfx gMiniblinSkel_body_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_head_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_leftear1_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_leftear2_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_rightear1_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_rightear2_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_hip_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_upperleg_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_leg_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_foot_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_hip_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_upperleg_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_leg_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_foot_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_tail1_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_tailend_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_mouth_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_shoulder_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_upperarm_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_arm_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_hand_l_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_shoulder_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_upperarm_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_arm_r_mesh_layer_Opaque[];
extern Gfx gMiniblinSkel_hand_r_mesh_layer_Opaque[];
extern FlexSkeletonHeader gMiniblinSkel;
#define GMINIBLINSKEL_BONE_POS_LIMB 0
#define GMINIBLINSKEL_BONE_ROT_LIMB 1
#define GMINIBLINSKEL_BODY_LIMB 2
#define GMINIBLINSKEL_HEAD_LIMB 3
#define GMINIBLINSKEL_LEFTEAR1_LIMB 4
#define GMINIBLINSKEL_LEFTEAR2_LIMB 5
#define GMINIBLINSKEL_RIGHTEAR1_LIMB 6
#define GMINIBLINSKEL_RIGHTEAR2_LIMB 7
#define GMINIBLINSKEL_HIP_L_LIMB 8
#define GMINIBLINSKEL_UPPERLEG_L_LIMB 9
#define GMINIBLINSKEL_LEG_L_LIMB 10
#define GMINIBLINSKEL_FOOT_L_LIMB 11
#define GMINIBLINSKEL_HIP_R_LIMB 12
#define GMINIBLINSKEL_UPPERLEG_R_LIMB 13
#define GMINIBLINSKEL_LEG_R_LIMB 14
#define GMINIBLINSKEL_FOOT_R_LIMB 15
#define GMINIBLINSKEL_HIPBACK_LIMB 16
#define GMINIBLINSKEL_TAIL1_LIMB 17
#define GMINIBLINSKEL_TAILEND_LIMB 18
#define GMINIBLINSKEL_MOUTH_LIMB 19
#define GMINIBLINSKEL_SHOULDER_L_LIMB 20
#define GMINIBLINSKEL_UPPERARM_L_LIMB 21
#define GMINIBLINSKEL_ARM_L_LIMB 22
#define GMINIBLINSKEL_HAND_L_LIMB 23
#define GMINIBLINSKEL_SHOULDER_R_LIMB 24
#define GMINIBLINSKEL_UPPERARM_R_LIMB 25
#define GMINIBLINSKEL_ARM_R_LIMB 26
#define GMINIBLINSKEL_HAND_R_LIMB 27
#define GMINIBLINSKEL_NUM_LIMBS 28

#endif
