    OBJECT_ICE_OBJECTS, // 0
    OBJECT_FZ, // 1
    OBJECT_BOX, // 2
    OBJECT_GI_HEART, // 3
    OBJECT_EFC_FLASH, // 4
    OBJECT_FIREFLY, // 5
    OBJECT_TRAP, // 6
    OBJECT_ST, // 7
    OBJECT_GI_SUTARU, // 8

