    SCENE_CMD_QUEST_HEADER_LIST(questHeaders),
    SCENE_CMD_ECHO_SETTINGS(10),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_DUNGEON, ROOM_ENV_DEFAULT, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(true /* no skybox */, true /* no sun/moon */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 0 /* time doesn't move */),
    SCENE_CMD_ROOM_SHAPE(&jyasinzou_room_16_030000B0_RoomShapeCullable),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(jyasinzou_room_16_03000040_ObjectList), jyasinzou_room_16_03000040_ObjectList),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(jyasinzou_room_16_03000048_ActorEntryList), jyasinzou_room_16_03000048_ActorEntryList),
    SCENE_CMD_END(),
