    SCENE_CMD_QUEST_HEADER_LIST(questHeaders),
    SCENE_CMD_ALTERNATE_HEADER_LIST(ice_doukutu_room_0_03000048_AltHeaders),
    SCENE_CMD_ECHO_SETTINGS(7),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_DUNGEON, ROOM_ENV_COLD, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(true /* no skybox */, true /* no sun/moon */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 0 /* time doesn't move */),
    SCENE_CMD_ROOM_SHAPE(&ice_doukutu_room_0_030000C0_RoomShapeNormal),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(ice_doukutu_room_0_03000058_ObjectList), ice_doukutu_room_0_03000058_ObjectList),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(ice_doukutu_room_0_03000060_ActorEntryList), ice_doukutu_room_0_03000060_ActorEntryList),
    SCENE_CMD_END(),
