    OBJECT_JYA_OBJ, // 0
    OBJECT_JYA_DOOR, // 1
    OBJECT_BOX, // 2
    OBJECT_EFC_FLASH, // 3
    OBJECT_DEMO_KEKKAI, // 4
    OBJECT_D_HSBLOCK, // 5
    OBJECT_DOOR_KILLER, // 6
    OBJECT_DDAN_OBJECTS, // 7
    OBJECT_BW, // 8

