    OBJECT_JYA_OBJ, // 0
    OBJECT_JYA_DOOR, // 1
    OBJECT_MIR_RAY, // 2
    OBJECT_BDOOR, // 3
    OBJECT_SYOKUDAI, // 4
    OBJECT_LIGHTSWITCH, // 5
    OBJECT_FIREFLY, // 6
    OBJECT_BW, // 7
    OBJECT_WALLMASTER, // 8
    OBJECT_BOX, // 9
    OBJECT_EFC_FLASH, // 10

