    OBJECT_MENKURI_OBJECTS, // 0
    OBJECT_DDAN_OBJECTS, // 1
    OBJECT_BB, // 2
    OBJECT_D_HSBLOCK, // 3
    OBJECT_SYOKUDAI, // 4
    OBJECT_BOX, // 5
    OBJECT_DEMO_KEKKAI, // 6
    OBJECT_KIBAKO2, // 7
    OBJECT_WALLMASTER, // 8

