    OBJECT_MENKURI_OBJECTS, // 0
    OBJECT_HIDAN_OBJECTS, // 1
    OBJECT_GOROIWA, // 2
    OBJECT_BOX, // 3
    OBJECT_EFC_FLASH, // 4
    OBJECT_DOOR_KILLER, // 5
    OBJECT_D_HSBLOCK, // 6
    OBJECT_WALLMASTER, // 7

