    OBJECT_JYA_OBJ, // 0
    OBJECT_JYA_DOOR, // 1
    OBJECT_MIR_RAY, // 2
    OBJECT_LIGHTSWITCH, // 3
    OBJECT_BOX, // 4
    OBJECT_DODOJR, // 5
    OBJECT_MIZU_OBJECTS, // 6
    OBJECT_VM, // 7
    OBJECT_FIREFLY, // 8
    OBJECT_RR, // 9
    OBJECT_GI_SHIELD_1, // 10
    OBJECT_GI_SHIELD_2, // 11
    OBJECT_GI_CLOTHES, // 12

