    OBJECT_JYA_OBJ, // 0
    OBJECT_JYA_DOOR, // 1
    OBJECT_MIR_RAY, // 2
    OBJECT_BDOOR, // 3
    OBJECT_SYOKUDAI, // 4
    OBJECT_LIGHTSWITCH, // 5
    OBJECT_BOX, // 6
    OBJECT_KA, // 7
    OBJECT_TIMEBLOCK, // 8
    OBJECT_EFC_TW, // 9
    OBJECT_JYA_IRON, // 10
    OBJECT_WALLMASTER, // 11
    OBJECT_KIBAKO2, // 12

