    OBJECT_JYA_OBJ, // 0
    OBJECT_JYA_DOOR, // 1
    OBJECT_MIR_RAY, // 2
    OBJECT_LIGHTSWITCH, // 3
    OBJECT_BOX, // 4
    OBJECT_BB, // 5
    OBJECT_WALLMASTER, // 6
    OBJECT_ST, // 7
    OBJECT_GI_SUTARU, // 8
    OBJECT_D_HSBLOCK, // 9
    OBJECT_DEMO_KEKKAI, // 10

