    SCENE_CMD_QUEST_HEADER_LIST(questHeaders),
    SCENE_CMD_ECHO_SETTINGS(10),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_DUNGEON, ROOM_ENV_DEFAULT, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(true /* no skybox */, true /* no sun/moon */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 0 /* time doesn't move */),
    SCENE_CMD_ROOM_SHAPE(&Bmori1_room_20_030000B0_RoomShapeCullable),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(Bmori1_room_20_03000040_ObjectList), Bmori1_room_20_03000040_ObjectList),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(Bmori1_room_20_03000054_ActorEntryList), Bmori1_room_20_03000054_ActorEntryList),
    SCENE_CMD_END(),
