    OBJECT_DDAN_OBJECTS, // 0
    OBJECT_BWALL, // 1
    OBJECT_BOMBF, // 2
    OBJECT_SYOKUDAI, // 3
    OBJECT_D_ELEVATOR, // 4
    OBJECT_KIBAKO2, // 5
    OBJECT_ST, // 6
    OBJECT_VM, // 7
    OBJECT_SHOPNUTS, // 8
    OBJECT_DEKUBABA, // 9

