    OBJECT_MORI_TEX, // 0
    OBJECT_MORI_OBJECTS, // 1
    OBJECT_PO_SISTERS, // 2
    OBJECT_SYOKUDAI, // 3
    OBJECT_BOX, // 4
    OBJECT_EFC_FLASH, // 5
    OBJECT_MORI_HINERI1, // 6
    OBJECT_MORI_HINERI1A, // 7

