    OBJECT_MORI_TEX, // 0
    OBJECT_MORI_OBJECTS, // 1
    OBJECT_D_HSBLOCK, // 2
    OBJECT_KA, // 3
    OBJECT_ST, // 4
    OBJECT_SYOKUDAI, // 5
    OBJECT_BOX, // 6
    OBJECT_OKUTA, // 7
    OBJECT_DEKUBABA, // 8
    OBJECT_GI_HEART, // 9
    OBJECT_GI_SUTARU, // 10

