    SCENE_CMD_ECHO_SETTINGS(10),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_NORMAL, ROOM_ENV_WARM, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(false /* skybox enabled */, false /* sun/moon enabled */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 10),
    SCENE_CMD_WIND_SETTINGS(6, 2, 255, 130),
    SCENE_CMD_ROOM_SHAPE(&spot11_room_0_030002F0_RoomShapeCullable),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(cq_objects_header2), cq_objects_header2),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(cq_actors_header2), cq_actors_header2),
    SCENE_CMD_END(),
