    SCENE_CMD_ECHO_SETTINGS(0),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_NORMAL, ROOM_ENV_DEFAULT, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(false /* skybox enabled */, true /* no sun/moon */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 0 /* time doesn't move */),
    SCENE_CMD_ROOM_SHAPE(&spot05_room_0_03000220_RoomShapeCullable),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(cq_objects_header2), cq_objects_header2),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(cq_actors_header2), cq_actors_header2),
    SCENE_CMD_END(),
