    OBJECT_HAKACH_OBJECTS, // 0
    OBJECT_HAKA_DOOR, // 1
    OBJECT_BOX, // 2
    OBJECT_EFC_FLASH, // 3
    OBJECT_ST, // 4
    OBJECT_KUSA, // 5
    OBJECT_FIREFLY, // 6
    OBJECT_BOMBF, // 7
    OBJECT_BOMBIWA, // 8
    OBJECT_GI_SUTARU, // 9

