    OBJECT_HAKACH_OBJECTS, // 0
    OBJECT_HAKA_DOOR, // 1
    OBJECT_BOX, // 2
    OBJECT_SYOKUDAI, // 3
    OBJECT_RD, // 4
    OBJECT_ST, // 5
    OBJECT_GI_SUTARU, // 6
    OBJECT_MIZU_OBJECTS, // 7
    OBJECT_BOMBIWA, // 8
    OBJECT_WALLMASTER, // 9
    OBJECT_GI_KEY, // 10
    OBJECT_GOROIWA, // 11
    OBJECT_EFC_FLASH, // 12
    OBJECT_GI_HEART, // 13

