beginseg
    name "ovl_Effect_Ss_Dinofos_Fire"
    compress
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dinofos_Fire/z_eff_ss_dinofos_fire.o"
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dinofos_Fire/ovl_Effect_Ss_Dinofos_Fire_reloc.o"
endseg

beginseg
    name "ovl_Item_Shield_Young"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Shield/z_item_shield_young.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Shield/ovl_Item_Shield_Young_reloc.o"
endseg

beginseg
    name "ovl_En_Invisible_Ruppe"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Invisible_Ruppe/ovl_En_Invisible_Ruppe_reloc.o"
endseg

beginseg
    name "ovl_En_Hit_Tag"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hit_Tag/z_en_hit_tag.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hit_Tag/ovl_En_Hit_Tag_reloc.o"
endseg

beginseg
    name "ovl_Obj_HsStump"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_HsStump/z_obj_hsstump.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_HsStump/ovl_Obj_HsStump_reloc.o"
endseg

beginseg
    name "ovl_Obj_Flowerpot"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Flowerpot/ovl_Obj_Flowerpot_reloc.o"
endseg

beginseg
    name "ovl_Obj_Kibako3"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Kibako3/z_obj_kibako3.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Kibako3/ovl_Obj_Kibako3_reloc.o"
endseg

beginseg
    name "ovl_Bg_Ladder"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ladder/z_bg_ladder.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ladder/ovl_Bg_Ladder_reloc.o"
endseg

beginseg
    name "ovl_Bg_Icefloe"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Icefloe/z_bg_icefloe.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Icefloe/ovl_Bg_Icefloe_reloc.o"
endseg

beginseg
    name "ovl_Obj_Visiblock"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Visiblock/z_obj_visiblock.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Visiblock/ovl_Obj_Visiblock_reloc.o"
endseg

beginseg
    name "ovl_Dm_Char01"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Dm_Char01/z_dm_char01.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Dm_Char01/ovl_Dm_Char01_reloc.o"
endseg

beginseg
    name "ovl_Bg_Wood_Pillar"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Wood_Pillar/z_bg_wood_pillar.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Wood_Pillar/ovl_Bg_Wood_Pillar_reloc.o"
endseg

beginseg
    name "ovl_Door_Spiral"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Spiral/z_door_spiral.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Spiral/ovl_Door_Spiral_reloc.o"
endseg

beginseg
    name "ovl_Bg_Teleporter"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Teleporter/z_bg_teleporter.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Teleporter/ovl_Bg_Teleporter_reloc.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Hasi2"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Hasi2/z_bg_ydan_hasi2.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Hasi2/ovl_Bg_Ydan_Hasi2_reloc.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Maruta2"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Maruta2/z_bg_ydan_maruta2.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Maruta2/ovl_Bg_Ydan_Maruta2_reloc.o"
endseg

beginseg
    name "ovl_Obj_Lost_Woods"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Lost_Woods/z_obj_lost_woods.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Lost_Woods/ovl_Obj_Lost_Woods_reloc.o"
endseg

beginseg
    name "ovl_Obj_Purify"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Purify/z_obj_purify.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Purify/ovl_Obj_Purify_reloc.o"
endseg

beginseg
    name "ovl_Obj_Raillift"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Raillift/ovl_Obj_Raillift_reloc.o"
endseg

beginseg
    name "ovl_Bg_Dkjail_Ivy"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dkjail_Ivy/z_bg_dkjail_ivy.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dkjail_Ivy/ovl_Bg_Dkjail_Ivy_reloc.o"
endseg

beginseg
    name "ovl_Bg_Numa_Hana"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Numa_Hana/z_bg_numa_hana.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Numa_Hana/ovl_Bg_Numa_Hana_reloc.o"
endseg

beginseg
    name "ovl_Obj_Pzlblock"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Pzlblock/z_obj_pzlblock.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Pzlblock/ovl_Obj_Pzlblock_reloc.o"
endseg

beginseg
    name "ovl_En_Horse_Young"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Young/z_en_horse_young.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Young/ovl_En_Horse_Young_reloc.o"
endseg

beginseg
    name "ovl_En_Tanron1"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tanron1/z_en_tanron1.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tanron1/ovl_En_Tanron1_reloc.o"
endseg

beginseg
    name "ovl_En_Raf"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Raf/z_en_raf.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Raf/ovl_En_Raf_reloc.o"
endseg

beginseg
    name "ovl_En_Dinofos"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dinofos/ovl_En_Dinofos_reloc.o"
endseg

beginseg
    name "ovl_En_BuffDeku"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_BuffDeku/z_en_buffdeku.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_BuffDeku/ovl_En_BuffDeku_reloc.o"
endseg

beginseg
    name "ovl_En_Hammergeist"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hammergeist/z_en_hammergeist.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hammergeist/ovl_En_Hammergeist_reloc.o"
endseg

beginseg
    name "ovl_En_Miniblin"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Miniblin/z_en_miniblin.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Miniblin/ovl_En_Miniblin_reloc.o"
endseg

beginseg
    name "ovl_En_Slim"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Slim/z_en_slim.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Slim/ovl_En_Slim_reloc.o"
endseg

beginseg
    name "ovl_En_Beast"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Beast/z_en_beast.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Beast/ovl_En_Beast_reloc.o"
endseg

beginseg
    name "ovl_En_Mkk"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mkk/z_en_mkk.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mkk/ovl_En_Mkk_reloc.o"
endseg

beginseg
    name "ovl_En_Bee"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bee/z_en_bee.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bee/ovl_En_Bee_reloc.o"
endseg

beginseg
    name "ovl_En_Grasshopper"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Grasshopper/ovl_En_Grasshopper_reloc.o"
endseg

beginseg
    name "ovl_En_Kame"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kame/z_en_kame.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kame/ovl_En_Kame_reloc.o"
endseg

beginseg
    name "ovl_En_Stalm"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Stalm/z_en_stalm.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Stalm/ovl_En_Stalm_reloc.o"
endseg

beginseg
    name "ovl_Bg_Ganon_Ladder"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ganon_Ladder/z_bg_ganon_ladder.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ganon_Ladder/ovl_Bg_Ganon_Ladder_reloc.o"
endseg

beginseg
    name "ovl_En_Ganon_Sword"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ganon_Sword/z_en_ganon_sword.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ganon_Sword/ovl_En_Ganon_Sword_reloc.o"
endseg

beginseg
    name "ovl_En_Go3"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Go3/z_en_go3.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Go3/ovl_En_Go3_reloc.o"
endseg

beginseg
    name "ovl_En_Jg"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Jg/z_en_jg.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Jg/ovl_En_Jg_reloc.o"
endseg
