beginseg
    name "road_to_swamp_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/road_to_swamp/road_to_swamp_scene.o"
    number 2
endseg

beginseg
    name "road_to_swamp_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/road_to_swamp/road_to_swamp_room_0.o"
    number 3
endseg

beginseg
    name "road_to_ikana_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/road_to_ikana/road_to_ikana_scene.o"
    number 2
endseg

beginseg
    name "road_to_ikana_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/road_to_ikana/road_to_ikana_room_0.o"
    number 3
endseg

beginseg
    name "milk_road_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/milk_road/milk_road_scene.o"
    number 2
endseg

beginseg
    name "milk_road_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/milk_road/milk_road_room_0.o"
    number 3
endseg

beginseg
    name "mountain_village_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/mountain_village/mountain_village_scene.o"
    number 2
endseg

beginseg
    name "mountain_village_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/mountain_village/mountain_village_room_0.o"
    number 3
endseg

beginseg
    name "mountain_village_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/mountain_village/mountain_village_room_1.o"
    number 3
endseg

beginseg
    name "woodfall_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/woodfall/woodfall_scene.o"
    number 2
endseg

beginseg
    name "woodfall_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/woodfall/woodfall_room_0.o"
    number 3
endseg

beginseg
    name "path_to_goron_village_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/path_to_goron_village/path_to_goron_village_scene.o"
    number 2
endseg

beginseg
    name "path_to_goron_village_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/path_to_goron_village/path_to_goron_village_room_0.o"
    number 3
endseg

beginseg
    name "goron_village_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/goron_village/goron_village_scene.o"
    number 2
endseg

beginseg
    name "goron_village_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/goron_village/goron_village_room_0.o"
    number 3
endseg

beginseg
    name "goron_village_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/goron_village/goron_village_room_1.o"
    number 3
endseg

beginseg
    name "goron_shrine_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/goron_shrine/goron_shrine_scene.o"
    number 2
endseg

beginseg
    name "goron_shrine_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/goron_shrine/goron_shrine_room_0.o"
    number 3
endseg

beginseg
    name "goron_shrine_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/goron_shrine/goron_shrine_room_1.o"
    number 3
endseg

beginseg
    name "dawngrove_village_scene"
    include "$(BUILD_DIR)/assets/scenes/overworld/dawngrove_village/dawngrove_village_scene.o"
    number 2
endseg

beginseg
    name "dawngrove_village_room_0"
    include "$(BUILD_DIR)/assets/scenes/overworld/dawngrove_village/dawngrove_village_room_0.o"
    number 3
endseg

beginseg
    name "dawngrove_scene"
    include "$(BUILD_DIR)/assets/scenes/overworld/dawngrove/dawngrove_scene.o"
    number 2
endseg

beginseg
    name "dawngrove_room_0"
    include "$(BUILD_DIR)/assets/scenes/overworld/dawngrove/dawngrove_room_0.o"
    number 3
endseg

beginseg
    name "dawngrove_room_1"
    include "$(BUILD_DIR)/assets/scenes/overworld/dawngrove/dawngrove_room_1.o"
    number 3
endseg

beginseg
    name "dawngrove_room_2"
    include "$(BUILD_DIR)/assets/scenes/overworld/dawngrove/dawngrove_room_2.o"
    number 3
endseg

beginseg
    name "ikana_canyon_scene"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_canyon/ikana_canyon_scene.o"
    number 2
endseg

beginseg
    name "ikana_canyon_room_0"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_canyon/ikana_canyon_room_0.o"
    number 3
endseg

beginseg
    name "ikana_canyon_room_2"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_canyon/ikana_canyon_room_2.o"
    number 3
endseg

beginseg
    name "ikana_canyon_room_3"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_canyon/ikana_canyon_room_3.o"
    number 3
endseg

beginseg
    name "ikana_canyon_room_4"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_canyon/ikana_canyon_room_4.o"
    number 3
endseg

beginseg
    name "ikana_graveyard_scene"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_graveyard/ikana_graveyard_scene.o"
    number 2
endseg

beginseg
    name "ikana_graveyard_room_0"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_graveyard/ikana_graveyard_room_0.o"
    number 3
endseg

beginseg
    name "ikana_graveyard_room_1"
    include "$(BUILD_DIR)/assets/scenes/overworld/ikana_graveyard/ikana_graveyard_room_1.o"
    number 3
endseg

beginseg
    name "old_lost_woods_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/old_lost_woods/old_lost_woods_scene.o"
    number 2
endseg

beginseg
    name "old_lost_woods_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/old_lost_woods/old_lost_woods_room_0.o"
    number 3
endseg

beginseg
    name "grottos2_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/grottos2_scene.o"
    number 2
endseg

beginseg
    name "grottos2_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/grottos2_room_6.o"
    number 3
endseg

beginseg
    name "grottos2_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/grottos2_room_7.o"
    number 3
endseg

beginseg
    name "grottos2_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/grottos2_room_8.o"
    number 3
endseg

beginseg
    name "grottos2_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/grottos2_room_10.o"
    number 3
endseg

beginseg
    name "grottos2_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/grottos2_room_13.o"
    number 3
endseg

beginseg
    name "dawngrove_grottos_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/dawngrove_grottos_room_0.o"
    number 3
endseg

beginseg
    name "cave_passage_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grottos2/cave_passage_room_0.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_scene.o"
    number 2
endseg

beginseg
    name "swamp_spider_house_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_0.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_1.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_2.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_3.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_4.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_5.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_scene.o"
    number 2
endseg

beginseg
    name "fairy_deku_tree_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_0.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_1.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_2.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_3.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_4.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_5.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_6.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_7.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_8.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_9.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_10.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_11.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_12.o"
    number 3
endseg

beginseg
    name "fairy_deku_tree_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/fairy_deku_tree/fairy_deku_tree_room_13.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_scene.o"
    number 2
endseg

beginseg
    name "old_dodongos_cavern_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_0.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_1.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_2.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_3.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_4.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_5.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_6.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_7.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_8.o"
    number 3
endseg

beginseg
    name "old_dodongos_cavern_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/old_dodongos_cavern/old_dodongos_cavern_room_9.o"
    number 3
endseg

beginseg
    name "woodfall_temple_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_scene.o"
    number 2
endseg

beginseg
    name "woodfall_temple_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_0.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_1.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_2.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_3.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_4.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_5.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_6.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_7.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_8.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_9.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_10.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_11.o"
    number 3
endseg

beginseg
    name "woodfall_temple_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple/woodfall_temple_room_12.o"
    number 3
endseg

beginseg
    name "woodfall_temple_boss_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple_boss/woodfall_temple_boss_scene.o"
    number 2
endseg

beginseg
    name "woodfall_temple_boss_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/woodfall_temple_boss/woodfall_temple_boss_room_0.o"
    number 3
endseg

beginseg
    name "beneath_the_graveyard_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/beneath_the_graveyard/beneath_the_graveyard_scene.o"
    number 2
endseg

beginseg
    name "beneath_the_graveyard_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/beneath_the_graveyard/beneath_the_graveyard_room_0.o"
    number 3
endseg

beginseg
    name "beneath_the_graveyard_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/beneath_the_graveyard/beneath_the_graveyard_room_1.o"
    number 3
endseg

beginseg
    name "beneath_the_graveyard_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/beneath_the_graveyard/beneath_the_graveyard_room_2.o"
    number 3
endseg

beginseg
    name "beneath_the_graveyard_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/beneath_the_graveyard/beneath_the_graveyard_room_3.o"
    number 3
endseg

beginseg
    name "beneath_the_graveyard_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/beneath_the_graveyard/beneath_the_graveyard_room_4.o"
    number 3
endseg

beginseg
    name "dawngrove_inn_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_scene.o"
    number 2
endseg

beginseg
    name "dawngrove_inn_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_room_0.o"
    number 3
endseg

beginseg
    name "dawngrove_inn_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_room_1.o"
    number 3
endseg

beginseg
    name "dawngrove_inn_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_room_2.o"
    number 3
endseg

beginseg
    name "dawngrove_inn_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_room_3.o"
    number 3
endseg

beginseg
    name "dawngrove_inn_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_room_4.o"
    number 3
endseg

beginseg
    name "dawngrove_inn_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_inn/dawngrove_inn_room_5.o"
    number 3
endseg

beginseg
    name "dawngrove_house_1_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_house_1/dawngrove_house_1_scene.o"
    number 2
endseg

beginseg
    name "dawngrove_house_1_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_house_1/dawngrove_house_1_room_0.o"
    number 3
endseg

beginseg
    name "dawngrove_house_2_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_house_2/dawngrove_house_2_scene.o"
    number 2
endseg

beginseg
    name "dawngrove_house_2_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/dawngrove_house_2/dawngrove_house_2_room_0.o"
    number 3
endseg

beginseg
    name "dawngrove_shop_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/shops/dawngrove_shop/dawngrove_shop_scene.o"
    number 2
endseg

beginseg
    name "dawngrove_shop_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/shops/dawngrove_shop/dawngrove_shop_room_0.o"
    number 3
endseg

beginseg
    name "mountain_smithy_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/mountain_smithy/mountain_smithy_scene.o"
    number 2
endseg

beginseg
    name "mountain_smithy_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/indoors/mountain_smithy/mountain_smithy_room_0.o"
    number 3
endseg