beginseg
    name "object_link_young"
    compress
    include "$(BUILD_DIR)/assets/objects/object_link_child/object_link_young.o"
    number 6
endseg

beginseg
    name "object_ladder"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ladder/object_ladder.o"
    number 6
endseg

beginseg
    name "object_bridge_piece"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bridge_piece/object_bridge_piece.o"
    number 6
endseg

beginseg
    name "object_deku_platforms"
    compress
    include "$(BUILD_DIR)/assets/objects/object_deku_platforms/object_deku_platforms.o"
    number 6
endseg

beginseg
    name "object_deku_door"
    compress
    include "$(BUILD_DIR)/assets/objects/object_deku_door/object_deku_door.o"
    number 6
endseg

beginseg
    name "object_lost_woods"
    compress
    include "$(BUILD_DIR)/assets/objects/object_lost_woods/object_lost_woods.o"
    number 6
endseg

beginseg
    name "object_gi_gold_dust"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_gold_dust/object_gi_gold_dust.o"
    number 6
endseg

beginseg
    name "object_gi_heros_bow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_heros_bow/object_gi_heros_bow.o"
    number 6
endseg

beginseg
    name "object_gi_hookshot_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_hookshot_mm/object_gi_hookshot_mm.o"
    number 6
endseg

beginseg
    name "object_gi_sword_heros"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_sword_heros/object_gi_sword_heros.o"
    number 6
endseg

beginseg
    name "object_gi_longsword_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_longsword_mm/object_gi_longsword_mm.o"
    number 6
endseg

beginseg
    name "object_gi_shield_3_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_3_mm/object_gi_shield_3_mm.o"
    number 6
endseg

beginseg
    name "object_gi_shield_4"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_4/object_gi_shield_4.o"
    number 6
endseg

beginseg
    name "object_horse_young"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse_young/object_horse_young.o"
    number 6
endseg

beginseg
    name "object_dinofos"
    compress
    number 6
    include "$(BUILD_DIR)/assets/objects/object_dinofos/object_dinofos.o"
endseg

beginseg
    name "object_buffdeku"
    compress
    include "$(BUILD_DIR)/assets/objects/object_buffdeku/object_buffdeku.o"
    number 6
endseg

beginseg
    name "object_hammergeist"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hammergeist/object_hammergeist.o"
    number 6
endseg

beginseg
    name "object_miniblin"
    compress
    include "$(BUILD_DIR)/assets/objects/object_miniblin/object_miniblin.o"
    number 6
endseg

beginseg
    name "object_slime"
    compress
    include "$(BUILD_DIR)/assets/objects/object_slime/object_slime.o"
    number 6
endseg
