beginseg
    name "ovl_Effect_Ss_Dinofos_Fire"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/effects/ovl_Effect_Ss_Dinofos_Fire/z_eff_ss_dinofos_fire.o"
endseg

beginseg
    name "ovl_Item_Shield_Young"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Shield/z_item_shield_young.o"
endseg

beginseg
    name "ovl_En_Invisible_Ruppe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.o"
endseg

beginseg
    name "ovl_En_Hit_Tag"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hit_Tag/z_en_hit_tag.o"
endseg

beginseg
    name "ovl_Obj_HsStump"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_HsStump/z_obj_hsstump.o"
endseg

beginseg
    name "ovl_Obj_Flowerpot"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.o"
endseg

beginseg
    name "ovl_Obj_Kibako3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Kibako3/z_obj_kibako3.o"
endseg

beginseg
    name "ovl_Bg_Ladder"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ladder/z_bg_ladder.o"
endseg

beginseg
    name "ovl_Bg_Icefloe"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Icefloe/z_bg_icefloe.o"
endseg

beginseg
    name "ovl_Obj_Visiblock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Visiblock/z_obj_visiblock.o"
endseg

beginseg
    name "ovl_Dm_Char01"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Dm_Char01/z_dm_char01.o"
endseg

beginseg
    name "ovl_Bg_Wood_Pillar"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Wood_Pillar/z_bg_wood_pillar.o"
endseg

beginseg
    name "ovl_Door_Spiral"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Door_Spiral/z_door_spiral.o"
endseg

beginseg
    name "ovl_Bg_Teleporter"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Teleporter/z_bg_teleporter.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Hasi2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Hasi2/z_bg_ydan_hasi2.o"
endseg

beginseg
    name "ovl_Bg_Ydan_Maruta2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ydan_Maruta2/z_bg_ydan_maruta2.o"
endseg

beginseg
    name "ovl_Obj_Lost_Woods"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Lost_Woods/z_obj_lost_woods.o"
endseg

beginseg
    name "ovl_Bg_Breakwall2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Breakwall2/z_bg_breakwall2.o"
endseg

beginseg
    name "ovl_Bg_Dodoago2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dodoago2/z_bg_dodoago2.o"
endseg

beginseg
    name "ovl_Bg_Flame_Thrower"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Flame_Thrower/z_bg_flame_thrower.o"
endseg

beginseg
    name "ovl_Bg_Dblue_Waterfall"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dblue_Waterfall/z_bg_dblue_waterfall.o"
endseg

beginseg
    name "ovl_Obj_Crashbox"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Crashbox/z_obj_crashbox.o"
endseg

beginseg
    name "ovl_Obj_Floater"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Floater/z_obj_floater.o"
endseg

beginseg
    name "ovl_Obj_Purify"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Purify/z_obj_purify.o"
endseg

beginseg
    name "ovl_Obj_Raillift"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.o"
endseg

beginseg
    name "ovl_Bg_Dkjail_Ivy"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Dkjail_Ivy/z_bg_dkjail_ivy.o"
endseg

beginseg
    name "ovl_Bg_Numa_Hana"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Numa_Hana/z_bg_numa_hana.o"
endseg

beginseg
    name "ovl_Obj_Pzlblock"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Pzlblock/z_obj_pzlblock.o"
endseg

beginseg
    name "ovl_Obj_Syokudai2"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Obj_Syokudai2/z_obj_syokudai2.o"
endseg

beginseg
    name "ovl_En_Horse_Young"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Young/z_en_horse_young.o"
endseg

beginseg
    name "ovl_En_Tanron1"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Tanron1/z_en_tanron1.o"
endseg

beginseg
    name "ovl_En_Raf"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Raf/z_en_raf.o"
endseg

beginseg
    name "ovl_En_Dinofos"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.o"
endseg

beginseg
    name "ovl_En_BuffDeku"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_BuffDeku/z_en_buffdeku.o"
endseg

beginseg
    name "ovl_En_Hammergeist"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hammergeist/z_en_hammergeist.o"
endseg

beginseg
    name "ovl_En_Miniblin"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Miniblin/z_en_miniblin.o"
endseg

beginseg
    name "ovl_En_Slim"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Slim/z_en_slim.o"
endseg

beginseg
    name "ovl_En_Beast"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Beast/z_en_beast.o"
endseg

beginseg
    name "ovl_En_Spider"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Spider/z_en_spider.o"
endseg

beginseg
    name "ovl_En_Thefather"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Thefather/z_en_thefather.o"
endseg

beginseg
    name "ovl_En_Mkk"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Mkk/z_en_mkk.o"
endseg

beginseg
    name "ovl_En_Bee"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Bee/z_en_bee.o"
endseg

beginseg
    name "ovl_En_Grasshopper"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.o"
endseg

beginseg
    name "ovl_En_Kame"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Kame/z_en_kame.o"
endseg

beginseg
    name "ovl_En_Stalm"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Stalm/z_en_stalm.o"
endseg

beginseg
    name "ovl_Bg_Ganon_Ladder"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ganon_Ladder/z_bg_ganon_ladder.o"
endseg

beginseg
    name "ovl_En_Ganon_Sword"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Ganon_Sword/z_en_ganon_sword.o"
endseg

beginseg
    name "ovl_En_Go3"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Go3/z_en_go3.o"
endseg

beginseg
    name "ovl_En_Jg"
    compress
    flags OVERLAY
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Jg/z_en_jg.o"
endseg
