beginseg
    name "roadtolake_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/roadtolake/roadtolake_scene.o"
    number 2
endseg

beginseg
    name "roadtolake_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/roadtolake/roadtolake_room_0.o"
    number 3
endseg

beginseg
    name "roadtofortress_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/roadtofortress/roadtofortress_scene.o"
    number 2
endseg

beginseg
    name "roadtofortress_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/overworld/roadtofortress/roadtofortress_room_0.o"
    number 3
endseg

beginseg
    name "grotto_shortcuts_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grotto_shortcuts/grotto_shortcuts_scene.o"
    number 2
endseg

beginseg
    name "grotto_shortcuts_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/misc/grotto_shortcuts/grotto_shortcuts_room_0.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_scene.o"
    number 2
endseg

beginseg
    name "swamp_spider_house_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_0.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_1.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_2.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_3.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_4.o"
    number 3
endseg

beginseg
    name "swamp_spider_house_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons/swamp_spider_house/swamp_spider_house_room_5.o"
    number 3
endseg
