beginseg
    name "ovl_Item_Shield_Young"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Shield/z_item_shield_young.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Item_Shield/ovl_Item_Shield_Young_reloc.o"
endseg

beginseg
    name "ovl_En_Invisible_Ruppe"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Invisible_Ruppe/ovl_En_Invisible_Ruppe_reloc.o"
endseg

beginseg
    name "ovl_En_Hit_Tag"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hit_Tag/z_en_hit_tag.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hit_Tag/ovl_En_Hit_Tag_reloc.o"
endseg

beginseg
    name "ovl_Bg_Ladder"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ladder/z_bg_ladder.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_Bg_Ladder/ovl_Bg_Ladder_reloc.o"
endseg

beginseg
    name "ovl_En_Horse_Young"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Young/z_en_horse_young.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Horse_Young/ovl_En_Horse_Young_reloc.o"
endseg

beginseg
    name "ovl_En_BuffDeku"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_BuffDeku/z_en_buffdeku.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_BuffDeku/ovl_En_BuffDeku_reloc.o"
endseg

beginseg
    name "ovl_En_Hammergeist"
    compress
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hammergeist/z_en_hammergeist.o"
    include "$(BUILD_DIR)/src/overlays/actors/ovl_En_Hammergeist/ovl_En_Hammergeist_reloc.o"
endseg
