beginseg
    name "object_link_young"
    compress
    include "$(BUILD_DIR)/assets/objects/object_link_child/object_link_young.o"
    number 6
endseg

beginseg
    name "object_hsstump"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hsstump/object_hsstump.o"
    number 6
endseg

beginseg
    name "object_ladder"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ladder/object_ladder.o"
    number 6
endseg

beginseg
    name "object_mtoride"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mtoride/object_mtoride.o"
    number 6
endseg

beginseg
    name "object_wood_pillar"
    compress
    include "$(BUILD_DIR)/assets/objects/object_wood_pillar/object_wood_pillar.o"
    number 6
endseg

beginseg
    name "object_dekucity_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dekucity_obj/object_dekucity_obj.o"
    number 6
endseg

beginseg
    name "object_numa_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_numa_obj/object_numa_obj.o"
    number 6
endseg

beginseg
    name "object_raillift"
    compress
    include "$(BUILD_DIR)/assets/objects/object_raillift/object_raillift.o"
    number 6
endseg

beginseg
    name "object_dkjail_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dkjail_obj/object_dkjail_obj.o"
    number 6
endseg

beginseg
    name "object_bg_teleporter"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bg_teleporter/object_bg_teleporter.o"
    number 6
endseg

beginseg
    name "object_bridge_piece"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bridge_piece/object_bridge_piece.o"
    number 6
endseg

beginseg
    name "object_deku_platforms"
    compress
    include "$(BUILD_DIR)/assets/objects/object_deku_platforms/object_deku_platforms.o"
    number 6
endseg

beginseg
    name "object_deku_door"
    compress
    include "$(BUILD_DIR)/assets/objects/object_deku_door/object_deku_door.o"
    number 6
endseg

beginseg
    name "object_lost_woods"
    compress
    include "$(BUILD_DIR)/assets/objects/object_lost_woods/object_lost_woods.o"
    number 6
endseg

beginseg
    name "object_gi_gold_dust"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_gold_dust/object_gi_gold_dust.o"
    number 6
endseg

beginseg
    name "object_gi_heros_bow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_heros_bow/object_gi_heros_bow.o"
    number 6
endseg

beginseg
    name "object_gi_hookshot_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_hookshot_mm/object_gi_hookshot_mm.o"
    number 6
endseg

beginseg
    name "object_gi_feather"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_feather/object_gi_feather.o"
    number 6
endseg

beginseg
    name "object_gi_pendant"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_pendant/object_gi_pendant.o"
    number 6
endseg

beginseg
    name "object_gi_sword_1_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_sword_1_mm/object_gi_sword_1_mm.o"
    number 6
endseg

beginseg
    name "object_gi_sword_3_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_sword_3_mm/object_gi_sword_3_mm.o"
    number 6
endseg

beginseg
    name "object_gi_sword_4_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_sword_4_mm/object_gi_sword_4_mm.o"
    number 6
endseg

beginseg
    name "object_gi_shield_2_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_2_mm/object_gi_shield_2_mm.o"
    number 6
endseg

beginseg
    name "object_gi_shield_3_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_3_mm/object_gi_shield_3_mm.o"
    number 6
endseg

beginseg
    name "object_horse_young"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse_young/object_horse_young.o"
    number 6
endseg

beginseg
    name "object_kgy"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kgy/object_kgy.o"
    number 6
endseg

beginseg
    name "object_raf"
    compress
    include "$(BUILD_DIR)/assets/objects/object_raf/object_raf.o"
    number 6
endseg

beginseg
    name "object_dinofos"
    compress
    number 6
    include "$(BUILD_DIR)/assets/objects/object_dinofos/object_dinofos.o"
endseg

beginseg
    name "object_buffdeku"
    compress
    include "$(BUILD_DIR)/assets/objects/object_buffdeku/object_buffdeku.o"
    number 6
endseg

beginseg
    name "object_hammergeist"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hammergeist/object_hammergeist.o"
    number 6
endseg

beginseg
    name "object_miniblin"
    compress
    include "$(BUILD_DIR)/assets/objects/object_miniblin/object_miniblin.o"
    number 6
endseg

beginseg
    name "object_slime"
    compress
    include "$(BUILD_DIR)/assets/objects/object_slime/object_slime.o"
    number 6
endseg

beginseg
    name "object_beast"
    compress
    include "$(BUILD_DIR)/assets/objects/object_beast/object_beast.o"
    number 6
endseg

beginseg
    name "object_mkk"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mkk/object_mkk.o"
    number 6
endseg

beginseg
    name "object_grasshopper"
    compress
    include "$(BUILD_DIR)/assets/objects/object_grasshopper/object_grasshopper.o"
    number 6
endseg

beginseg
    name "object_tl"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tl/object_tl.o"
    number 6
endseg

beginseg
    name "object_stalm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_stalm/object_stalm.o"
    number 6
endseg

beginseg
    name "object_ganon_ladder"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon_ladder/object_ganon_ladder.o"
    number 6
endseg
