beginseg
    name "gameplay_keep"
    compress
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/hilite_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/link_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/player_pause_joint_tables.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/player_anim_headers.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/debug_models.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gArrow1_Anim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gArrow2_Anim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/arrow_skel.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unk_eff_blure_tex.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/bomb_body.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/bomb_cap.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/bombchu_body.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_bomb_explosion.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_fragments_1.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/boomerang.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/compass_arrow.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_ntsc_0xC880.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/lock_on_arrow.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/hilite3_tex.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_fragments_2_model.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_ntsc_0xCE60.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/shopkeeper_controls_tex.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/rock_fragments_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/rock_fragments_tex.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gDoorChildOpeningLeftAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gDoorChildOpeningRightAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gDoorAdultOpeningLeftAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/door_skel.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gDoorAdultOpeningRightAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_dust.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_flash.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/spin_attack.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x13700.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/fairy_anim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/fairy_skel.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x16A50.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/hilite4_tex.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x173D0.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gFishOutOfWaterAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x18610.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gFishInWaterAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_shockwave.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_bubble.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_fire_footprint.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unused_bubbles.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/lens_mask_tex.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_hitmark.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x21810.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_magma_bubble.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_water_ripple.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_spark_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_water_splash.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unknown_eff_stone.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_lightning.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_enemy_death_flame.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x32090.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x33090.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_ice_fragments.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x33910.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gBugCrawlAnim.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/bug_skel.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/cuttable_shrub.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/lens_flare.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_sparkles.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/hover_boots_circle.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/moon.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x38FB0.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_ntsc_0x39850.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unused_bomb_icon_model_ntsc.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unused_heart_icon_model_ntsc.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unused_arrow_icon_model_ntsc.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gLargerCubeCol.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/liftable_rock_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x39710.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gWideTallBlockCol.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/flat_block_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gTallBlockCol.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x39DF0.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/small_flat_block_col.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/flat_rot_block_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gLargerFlatBlockCol.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/small_cube_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/small_cube_col.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/tree_stump_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/grass_blades_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x3AC30.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/heart_piece_interior_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x3B1E0.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_ntsc_0x3C610.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unused_heart_container_icon_model_ntsc.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/rectangular_sign_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/directional_sign_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x3C870.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_ntsc_0x3FD80.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/drop_recovery_heart_tex.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/unused_heart_piece_icon_tex_ntsc.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/item_drop_dl.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x3F140.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/rupee.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/item_drops_ntsc.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/rupee_light_red_tex.o"
#if OOT_NTSC
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_ntsc_0x46A40.o"
#endif
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x42530.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x43530.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x44530.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x45530.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x45D30.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/sign_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/raindrop_model.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/shadow_foot.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/shadow_circle.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/shadow_horse.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x49F20.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x4A090.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/sun_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/sun_evening_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x4D160.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/lock_on_reticle.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_fire.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x4E660.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x515B0.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/dust_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/circle_glow_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_0x55DB0.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/eff_spark_textures.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_keep/gameplay_keep_extra.o"
    number 4
endseg

beginseg
    name "gameplay_field_keep"
    compress
    include "$(BUILD_DIR)/assets/objects/gameplay_field_keep/gameplay_field_keep.o"
    number 5
endseg

beginseg
    name "gameplay_dangeon_keep"
    compress
    include "$(BUILD_DIR)/assets/objects/gameplay_dangeon_keep/gameplay_dangeon_keep.o"
    include "$(BUILD_DIR)/assets/objects/gameplay_dangeon_keep/gameplay_dangeon_keep_extra.o"
    number 5
endseg

beginseg
    name "gameplay_object_exchange_static"
    compress
    include "$(BUILD_DIR)/baserom/gameplay_object_exchange_static.o"
endseg

beginseg
    name "object_link_boy"
    compress
    include "$(BUILD_DIR)/assets/objects/object_link_boy/object_link_boy.o"
    number 6
endseg

beginseg
    name "object_link_child"
    compress
    include "$(BUILD_DIR)/assets/objects/object_link_child/object_link_child.o"
    number 6
endseg

beginseg
    name "object_box"
    compress
    include "$(BUILD_DIR)/assets/objects/object_box/object_box.o"
    include "$(BUILD_DIR)/assets/objects/object_box/object_box_extra.o"
    number 6
endseg

beginseg
    name "object_okuta"
    compress
    include "$(BUILD_DIR)/assets/objects/object_okuta/object_okuta.o"
    number 6
endseg

beginseg
    name "object_poh"
    compress
    include "$(BUILD_DIR)/assets/objects/object_poh/object_poh.o"
    number 6
endseg

beginseg
    name "object_wallmaster"
    compress
    include "$(BUILD_DIR)/assets/objects/object_wallmaster/object_wallmaster.o"
    number 6
endseg

beginseg
    name "object_dy_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dy_obj/object_dy_obj.o"
    number 6
endseg

beginseg
    name "object_firefly"
    compress
    include "$(BUILD_DIR)/assets/objects/object_firefly/object_firefly.o"
    include "$(BUILD_DIR)/assets/objects/object_firefly/object_firefly_extra.o"
    number 6
endseg

beginseg
    name "object_dodongo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dodongo/object_dodongo.o"
    number 6
endseg

beginseg
    name "object_niw"
    compress
    include "$(BUILD_DIR)/assets/objects/object_niw/object_niw.o"
    number 6
endseg

beginseg
    name "object_tite"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tite/object_tite.o"
    include "$(BUILD_DIR)/assets/objects/object_tite/object_tite_extra.o"
    number 6
endseg

beginseg
    name "object_reeba"
    compress
    include "$(BUILD_DIR)/assets/objects/object_reeba/object_reeba.o"
    number 6
endseg

beginseg
    name "object_peehat"
    compress
    include "$(BUILD_DIR)/assets/objects/object_peehat/object_peehat.o"
    number 6
endseg

beginseg
    name "object_kingdodongo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kingdodongo/object_kingdodongo.o"
    include "$(BUILD_DIR)/assets/objects/object_kingdodongo/object_kingdodongo_extra.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_kingdodongo/object_kingdodongo_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_horse"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse/object_horse.o"
    number 6
endseg

beginseg
    name "object_zf"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zf/object_zf.o"
    number 6
endseg

beginseg
    name "object_goma"
    compress
    include "$(BUILD_DIR)/assets/objects/object_goma/object_goma.o"
    include "$(BUILD_DIR)/assets/objects/object_goma/object_goma_extra.o"
    include "$(BUILD_DIR)/assets/objects/object_goma/object_goma_title_card.o"
    number 6
endseg

beginseg
    name "object_zl1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zl1/object_zl1.o"
    number 6
endseg

beginseg
    name "object_gol"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gol/object_gol.o"
    number 6
endseg

beginseg
    name "object_bubble"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bubble/object_bubble.o"
    number 6
endseg

beginseg
    name "object_dodojr"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dodojr/object_dodojr.o"
    number 6
endseg

beginseg
    name "object_torch2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_torch2/object_torch2.o"
    number 6
endseg

beginseg
    name "object_bl"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bl/object_bl.o"
    include "$(BUILD_DIR)/assets/objects/object_bl/object_bl_extra.o"
    number 6
endseg

beginseg
    name "object_tp"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tp/object_tp.o"
    number 6
endseg

beginseg
    name "object_st"
    compress
    include "$(BUILD_DIR)/assets/objects/object_st/object_st.o"
    number 6
endseg

beginseg
    name "object_bw"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bw/object_bw.o"
    number 6
endseg

beginseg
    name "object_ei"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ei/object_ei.o"
    number 6
endseg

beginseg
    name "object_horse_normal"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse_normal/object_horse_normal.o"
    number 6
endseg

beginseg
    name "object_o_anime"
    compress
    include "$(BUILD_DIR)/assets/objects/object_o_anime/object_o_anime.o"
    number 6
endseg

beginseg
    name "object_spot04_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot04_objects/object_spot04_objects.o"
    number 6
endseg

beginseg
    name "object_ddan_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ddan_objects/object_ddan_objects.o"
    number 6
endseg

beginseg
    name "object_hidan_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hidan_objects/object_hidan_objects.o"
    number 6
endseg

beginseg
    name "object_horse_ganon"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse_ganon/object_horse_ganon.o"
    number 6
endseg

beginseg
    name "object_oA2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_oA2/object_oA2.o"
    number 6
endseg

beginseg
    name "object_spot00_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot00_objects/object_spot00_objects.o"
    include "$(BUILD_DIR)/assets/objects/object_spot00_objects/object_spot00_objects_extra.o"
    number 6
endseg

beginseg
    name "object_mb"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mb/object_mb.o"
    number 6
endseg

beginseg
    name "object_bombf"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bombf/object_bombf.o"
    number 6
endseg

beginseg
    name "object_sk2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_sk2/object_sk2.o"
    number 6
endseg

beginseg
    name "object_oE_anime"
    compress
    include "$(BUILD_DIR)/assets/objects/object_oE_anime/object_oE_anime.o"
    number 6
endseg

beginseg
    name "object_ydan_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ydan_objects/object_ydan_objects.o"
    number 6
endseg

beginseg
    name "object_gnd"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gnd/object_gnd.o"
    number 6
endseg

beginseg
    name "object_am"
    compress
    include "$(BUILD_DIR)/assets/objects/object_am/object_am.o"
    number 6
endseg

beginseg
    name "object_dekubaba"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dekubaba/object_dekubaba.o"
    number 6
endseg

beginseg
    name "object_jj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_jj/object_jj.o"
    number 6
endseg

beginseg
    name "object_horse_zelda"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse_zelda/object_horse_zelda.o"
    number 6
endseg

beginseg
    name "object_opening_demo1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_opening_demo1/object_opening_demo1.o"
    number 6
endseg

beginseg
    name "object_warp1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_warp1/object_warp1.o"
    number 6
endseg

beginseg
    name "object_dekunuts"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dekunuts/object_dekunuts.o"
    include "$(BUILD_DIR)/assets/objects/object_dekunuts/object_dekunuts_extra.o"
    number 6
endseg

beginseg
    name "object_oE3"
    compress
    include "$(BUILD_DIR)/assets/objects/object_oE3/object_oE3.o"
    number 6
endseg

beginseg
    name "object_menkuri_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_menkuri_objects/object_menkuri_objects.o"
    number 6
endseg

beginseg
    name "object_vali"
    compress
    include "$(BUILD_DIR)/assets/objects/object_vali/object_vali.o"
    number 6
endseg

beginseg
    name "object_oA10"
    compress
    include "$(BUILD_DIR)/assets/objects/object_oA10/object_oA10.o"
    number 6
endseg

beginseg
    name "object_mizu_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mizu_objects/object_mizu_objects.o"
    number 6
endseg

beginseg
    name "object_fhg"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fhg/object_fhg.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_fhg/object_fhg_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_ossan"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ossan/object_ossan.o"
    number 6
endseg

beginseg
    name "object_mori_hineri1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mori_hineri1/object_mori_hineri1.o"
    number 6
endseg

beginseg
    name "object_Bb"
    compress
    include "$(BUILD_DIR)/assets/objects/object_Bb/object_Bb.o"
    number 6
endseg

beginseg
    name "object_toki_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_toki_objects/object_toki_objects.o"
    number 6
endseg

beginseg
    name "object_yukabyun"
    compress
    include "$(BUILD_DIR)/assets/objects/object_yukabyun/gFloorTileEnemyDL.o"
    include "$(BUILD_DIR)/assets/objects/object_yukabyun/gFloorTileEnemyFragmentDL.o"
    number 6
endseg

beginseg
    name "object_zl2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zl2/object_zl2.o"
    number 6
endseg

beginseg
    name "object_mjin"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin/object_mjin.o"
    number 6
endseg

beginseg
    name "object_mjin_flash"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_flash/object_mjin_flash.o"
    number 6
endseg

beginseg
    name "object_mjin_dark"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_dark/object_mjin_dark.o"
    number 6
endseg

beginseg
    name "object_mjin_flame"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_flame/object_mjin_flame.o"
    number 6
endseg

beginseg
    name "object_mjin_ice"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_ice/object_mjin_ice.o"
    number 6
endseg

beginseg
    name "object_mjin_soul"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_soul/object_mjin_soul.o"
    number 6
endseg

beginseg
    name "object_mjin_wind"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_wind/object_mjin_wind.o"
    number 6
endseg

beginseg
    name "object_mjin_oka"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mjin_oka/object_mjin_oka.o"
    number 6
endseg

beginseg
    name "object_haka_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_haka_objects/object_haka_objects.o"
    number 6
endseg

beginseg
    name "object_spot06_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot06_objects/object_spot06_objects.o"
    number 6
endseg

beginseg
    name "object_ice_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ice_objects/object_ice_objects.o"
    number 6
endseg

beginseg
    name "object_relay_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_relay_objects/object_relay_objects.o"
    number 6
endseg

beginseg
    name "object_mori_hineri1a"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mori_hineri1a/object_mori_hineri1a.o"
    number 6
endseg

beginseg
    name "object_mori_hineri2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mori_hineri2/object_mori_hineri2.o"
    number 6
endseg

beginseg
    name "object_mori_hineri2a"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mori_hineri2a/object_mori_hineri2a.o"
    number 6
endseg

beginseg
    name "object_mori_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mori_objects/object_mori_objects.o"
    number 6
endseg

beginseg
    name "object_mori_tex"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mori_tex/object_mori_tex.o"
    number 8
endseg

beginseg
    name "object_spot08_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot08_obj/object_spot08_obj.o"
    number 6
endseg

beginseg
    name "object_warp2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_warp2/object_warp2.o"
    number 6
endseg

beginseg
    name "object_hata"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hata/object_hata.o"
    number 6
endseg

beginseg
    name "object_bird"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bird/object_bird.o"
    number 6
endseg

beginseg
    name "object_wood02"
    compress
    include "$(BUILD_DIR)/assets/objects/object_wood02/object_wood02.o"
    number 6
endseg

beginseg
    name "object_lightbox"
    compress
    include "$(BUILD_DIR)/assets/objects/object_lightbox/object_lightbox.o"
    number 6
endseg

beginseg
    name "object_pu_box"
    compress
    include "$(BUILD_DIR)/assets/objects/object_pu_box/object_pu_box.o"
    number 6
endseg

beginseg
    name "object_trap"
    compress
    include "$(BUILD_DIR)/assets/objects/object_trap/object_trap.o"
    number 6
endseg

beginseg
    name "object_im"
    compress
    include "$(BUILD_DIR)/assets/objects/object_im/object_im.o"
    number 6
endseg

beginseg
    name "object_ta"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonSitSleepingAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonStandAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonSkel.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonSitHandsUpAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonSitWakeUpAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonRunAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonSleepAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonRunTransitionAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ta/gTalonWakeUpAnim.o"
    number 6
endseg

beginseg
    name "object_tk"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tk/object_tk.o"
    number 6
endseg

beginseg
    name "object_xc"
    compress
    include "$(BUILD_DIR)/assets/objects/object_xc/object_xc.o"
    number 6
endseg

beginseg
    name "object_vm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_vm/object_vm.o"
    number 6
endseg

beginseg
    name "object_bv"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bv/object_bv.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_bv/object_bv_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_hakach_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hakach_objects/object_hakach_objects.o"
    number 6
endseg

beginseg
    name "object_efc_crystal_light"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_crystal_light/object_efc_crystal_light.o"
    number 6
endseg

beginseg
    name "object_efc_fire_ball"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_fire_ball/object_efc_fire_ball.o"
    number 6
endseg

beginseg
    name "object_efc_flash"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_flash/object_efc_flash.o"
    number 6
endseg

beginseg
    name "object_efc_lgt_shower"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_lgt_shower/object_efc_lgt_shower.o"
    number 6
endseg

beginseg
    name "object_efc_star_field"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_star_field/object_efc_star_field.o"
    number 6
endseg

beginseg
    name "object_god_lgt"
    compress
    include "$(BUILD_DIR)/assets/objects/object_god_lgt/object_god_lgt.o"
    number 6
endseg

beginseg
    name "object_light_ring"
    compress
    include "$(BUILD_DIR)/assets/objects/object_light_ring/object_light_ring.o"
    number 6
endseg

beginseg
    name "object_triforce_spot"
    compress
    include "$(BUILD_DIR)/assets/objects/object_triforce_spot/object_triforce_spot.o"
    number 6
endseg

beginseg
    name "object_bdan_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bdan_objects/object_bdan_objects.o"
    number 6
endseg

beginseg
    name "object_sd"
    compress
    include "$(BUILD_DIR)/assets/objects/object_sd/object_sd.o"
    number 6
endseg

beginseg
    name "object_rd"
    compress
    include "$(BUILD_DIR)/assets/objects/object_rd/object_rd.o"
    include "$(BUILD_DIR)/assets/objects/object_rd/object_rd_dance.o"
    number 6
endseg

beginseg
    name "object_po_sisters"
    compress
    include "$(BUILD_DIR)/assets/objects/object_po_sisters/object_po_sisters.o"
    number 6
endseg

beginseg
    name "object_heavy_object"
    compress
    include "$(BUILD_DIR)/assets/objects/object_heavy_object/object_heavy_object.o"
    number 6
endseg

beginseg
    name "object_gndd"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gndd/object_gndd.o"
    number 6
endseg

beginseg
    name "object_fd"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fd/object_fd.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_fd/object_fd_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_du"
    compress
    include "$(BUILD_DIR)/assets/objects/object_du/object_du.o"
    number 6
endseg

beginseg
    name "object_fw"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fw/object_fw.o"
    number 6
endseg

beginseg
    name "object_horse_link_child"
    compress
    include "$(BUILD_DIR)/assets/objects/object_horse_link_child/object_horse_link_child.o"
    number 6
endseg

beginseg
    name "object_spot02_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot02_objects/object_spot02_objects.o"
    number 6
endseg

beginseg
    name "object_haka"
    compress
    include "$(BUILD_DIR)/assets/objects/object_haka/object_haka.o"
    number 6
endseg

beginseg
    name "object_ru1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ru1/object_ru1.o"
    number 6
endseg

beginseg
    name "object_syokudai"
    compress
    include "$(BUILD_DIR)/assets/objects/object_syokudai/gGoldenTorchDL.o"
    include "$(BUILD_DIR)/assets/objects/object_syokudai/gWoodenTorchDL.o"
    include "$(BUILD_DIR)/assets/objects/object_syokudai/gTimedTorchDL.o"
    include "$(BUILD_DIR)/assets/objects/object_syokudai/textures.o"
    number 6
endseg

beginseg
    name "object_fd2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fd2/object_fd2.o"
    number 6
endseg

beginseg
    name "object_dh"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dh/object_dh.o"
    number 6
endseg

beginseg
    name "object_rl"
    compress
    include "$(BUILD_DIR)/assets/objects/object_rl/object_rl.o"
    number 6
endseg

beginseg
    name "object_efc_tw"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_tw/object_efc_tw.o"
    number 6
endseg

beginseg
    name "object_gi_key"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_key/object_gi_key.o"
    number 6
endseg

beginseg
    name "object_mir_ray"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mir_ray/object_mir_ray.o"
    include "$(BUILD_DIR)/assets/objects/object_mir_ray/object_mir_ray_extra.o"
    number 6
endseg

beginseg
    name "object_brob"
    compress
    include "$(BUILD_DIR)/assets/objects/object_brob/object_brob.o"
    number 6
endseg

beginseg
    name "object_gi_jewel"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_jewel/object_gi_jewel.o"
    number 6
endseg

beginseg
    name "object_spot09_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot09_obj/object_spot09_obj.o"
    number 6
endseg

beginseg
    name "object_spot18_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot18_obj/object_spot18_obj.o"
    number 6
endseg

beginseg
    name "object_bdoor"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bdoor/object_bdoor.o"
    number 6
endseg

beginseg
    name "object_spot17_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot17_obj/bombable_wall_dls.o"
    include "$(BUILD_DIR)/assets/objects/object_spot17_obj/gCraterBombableWallCol.o"
    include "$(BUILD_DIR)/assets/objects/object_spot17_obj/gCraterSmokeConeDL.o"
    include "$(BUILD_DIR)/assets/objects/object_spot17_obj/gCraterBombableWallCracksTex.o"
    number 6
endseg

beginseg
    name "object_shop_dungen"
    compress
    include "$(BUILD_DIR)/assets/objects/object_shop_dungen/object_shop_dungen.o"
    number 6
endseg

beginseg
    name "object_nb"
    compress
    include "$(BUILD_DIR)/assets/objects/object_nb/object_nb.o"
    number 6
endseg

beginseg
    name "object_mo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mo/object_mo.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_mo/object_mo_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_sb"
    compress
    include "$(BUILD_DIR)/assets/objects/object_sb/object_sb.o"
    number 6
endseg

beginseg
    name "object_gi_melody"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_melody/object_gi_melody.o"
    number 6
endseg

beginseg
    name "object_gi_heart"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_heart/object_gi_heart.o"
    number 6
endseg

beginseg
    name "object_gi_compass"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_compass/object_gi_compass.o"
    number 6
endseg

beginseg
    name "object_gi_bosskey"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bosskey/object_gi_bosskey.o"
    number 6
endseg

beginseg
    name "object_gi_medal"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_medal/object_gi_medal.o"
    number 6
endseg

beginseg
    name "object_gi_nuts"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_nuts/object_gi_nuts.o"
    number 6
endseg

beginseg
    name "object_sa"
    compress
    include "$(BUILD_DIR)/assets/objects/object_sa/object_sa.o"
    number 6
endseg

beginseg
    name "object_gi_hearts"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_hearts/object_gi_hearts.o"
    number 6
endseg

beginseg
    name "object_gi_arrowcase"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_arrowcase/object_gi_arrowcase.o"
    number 6
endseg

beginseg
    name "object_gi_bombpouch"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bombpouch/object_gi_bombpouch.o"
    number 6
endseg

beginseg
    name "object_in"
    compress
    include "$(BUILD_DIR)/assets/objects/object_in/object_in.o"
    number 6
endseg

beginseg
    name "object_tr"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tr/object_tr.o"
    number 6
endseg

beginseg
    name "object_spot16_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot16_obj/gDodongosCavernRockDL.o"
    include "$(BUILD_DIR)/assets/objects/object_spot16_obj/gDeathMountainRingDL.o"
    number 6
endseg

beginseg
    name "object_os_anime"
    compress
    include "$(BUILD_DIR)/assets/objects/object_os_anime/object_os_anime.o"
    number 6
endseg

beginseg
    name "object_gi_bottle"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bottle/object_gi_bottle.o"
    number 6
endseg

beginseg
    name "object_gi_stick"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_stick/object_gi_stick.o"
    number 6
endseg

beginseg
    name "object_gi_map"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_map/object_gi_map.o"
    number 6
endseg

beginseg
    name "object_oF1d_map"
    compress
    include "$(BUILD_DIR)/assets/objects/object_oF1d_map/object_oF1d_map.o"
    number 6
endseg

beginseg
    name "object_ru2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ru2/object_ru2.o"
    number 6
endseg

beginseg
    name "object_gi_shield_1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_1/object_gi_shield_1.o"
    number 6
endseg

beginseg
    name "object_dekujr"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dekujr/object_dekujr.o"
    number 6
endseg

beginseg
    name "object_gi_magicpot"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_magicpot/object_gi_magicpot.o"
    number 6
endseg

beginseg
    name "object_gi_bomb_1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bomb_1/object_gi_bomb_1.o"
    number 6
endseg

beginseg
    name "object_ma2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ma2/object_ma2.o"
    number 6
endseg

beginseg
    name "object_gi_purse"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_purse/object_gi_purse.o"
    number 6
endseg

beginseg
    name "object_hni"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hni/object_hni.o"
    number 6
endseg

beginseg
    name "object_tw"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tw/object_tw.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_tw/object_tw_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_rr"
    compress
    include "$(BUILD_DIR)/assets/objects/object_rr/object_rr.o"
    number 6
endseg

beginseg
    name "object_bxa"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bxa/object_bxa.o"
    number 6
endseg

beginseg
    name "object_anubice"
    compress
    include "$(BUILD_DIR)/assets/objects/object_anubice/object_anubice.o"
    number 6
endseg

beginseg
    name "object_gi_gerudo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_gerudo/object_gi_gerudo.o"
    number 6
endseg

beginseg
    name "object_gi_arrow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_arrow/object_gi_arrow.o"
    number 6
endseg

beginseg
    name "object_gi_bomb_2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bomb_2/object_gi_bomb_2.o"
    number 6
endseg

beginseg
    name "object_gi_egg"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_egg/object_gi_egg.o"
    number 6
endseg

beginseg
    name "object_gi_scale"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_scale/object_gi_scale.o"
    number 6
endseg

beginseg
    name "object_gi_shield_2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_2/object_gi_shield_2.o"
    number 6
endseg

beginseg
    name "object_gi_hookshot"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_hookshot/object_gi_hookshot.o"
    number 6
endseg

beginseg
    name "object_gi_ocarina"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_ocarina/object_gi_ocarina.o"
    number 6
endseg

beginseg
    name "object_gi_milk"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_milk/object_gi_milk.o"
    number 6
endseg

beginseg
    name "object_ma1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ma1/object_ma1.o"
    number 6
endseg

beginseg
    name "object_ganon"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon/object_ganon.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon/object_ganon_extra.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_ganon/object_ganon_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_sst"
    compress
    include "$(BUILD_DIR)/assets/objects/object_sst/object_sst.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_sst/object_sst_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_ny"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ny/object_ny.o"
    number 6
endseg

beginseg
    name "object_fr"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fr/object_fr.o"
    number 6
endseg

beginseg
    name "object_gi_pachinko"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_pachinko/object_gi_pachinko.o"
    number 6
endseg

beginseg
    name "object_gi_boomerang"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_boomerang/object_gi_boomerang.o"
    number 6
endseg

beginseg
    name "object_gi_bow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bow/object_gi_bow.o"
    number 6
endseg

beginseg
    name "object_gi_glasses"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_glasses/object_gi_glasses.o"
    number 6
endseg

beginseg
    name "object_gi_liquid"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_liquid/object_gi_liquid.o"
    number 6
endseg

beginseg
    name "object_ani"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ani/object_ani.o"
    number 6
endseg

beginseg
    name "object_demo_6k"
    compress
    include "$(BUILD_DIR)/assets/objects/object_demo_6k/object_demo_6k.o"
    number 6
endseg

beginseg
    name "object_gi_shield_3"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_shield_3/object_gi_shield_3.o"
    number 6
endseg

beginseg
    name "object_gi_letter"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_letter/object_gi_letter.o"
    number 6
endseg

beginseg
    name "object_spot15_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot15_obj/gLonLonMilkCrateDL.o"
    include "$(BUILD_DIR)/assets/objects/object_spot15_obj/gLonLonMilkCrateCol.o"
    include "$(BUILD_DIR)/assets/objects/object_spot15_obj/gLonLonCorralFenceDL.o"
    include "$(BUILD_DIR)/assets/objects/object_spot15_obj/gLonLonCorralFenceCol.o"
    include "$(BUILD_DIR)/assets/objects/object_spot15_obj/textures.o"
    number 6
endseg

beginseg
    name "object_jya_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_jya_obj/object_jya_obj.o"
    number 6
endseg

beginseg
    name "object_gi_clothes"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_clothes/object_gi_clothes.o"
    number 6
endseg

beginseg
    name "object_gi_bean"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bean/object_gi_bean.o"
    number 6
endseg

beginseg
    name "object_gi_fish"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_fish/object_gi_fish.o"
    number 6
endseg

beginseg
    name "object_gi_saw"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_saw/object_gi_saw.o"
    number 6
endseg

beginseg
    name "object_gi_hammer"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_hammer/object_gi_hammer.o"
    number 6
endseg

beginseg
    name "object_gi_grass"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_grass/object_gi_grass.o"
    number 6
endseg

beginseg
    name "object_gi_longsword"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_longsword/object_gi_longsword.o"
    number 6
endseg

beginseg
    name "object_spot01_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot01_objects/object_spot01_objects.o"
    number 6
endseg

beginseg
    name "object_md"
    compress
    include "$(BUILD_DIR)/assets/objects/object_md/object_md.o"
    number 6
endseg

beginseg
    name "object_km1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_km1/object_km1.o"
    number 6
endseg

beginseg
    name "object_kw1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kw1/object_kw1.o"
    number 6
endseg

beginseg
    name "object_zo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zo/gZoraHandsOnHipsTappingFootAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/gZoraOpenArmsAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/gZoraThrowRupeesAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/effect_bubbles.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/effect_splashes.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/gZoraSurfaceAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/gZoraIdleAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/gZoraSkel.o"
    include "$(BUILD_DIR)/assets/objects/object_zo/effect_ripples.o"
    number 6
endseg

beginseg
    name "object_kz"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kz/object_kz.o"
    number 6
endseg

beginseg
    name "object_umajump"
    compress
    include "$(BUILD_DIR)/assets/objects/object_umajump/gJumpableHorseFenceDL.o"
    include "$(BUILD_DIR)/assets/objects/object_umajump/gJumpableHorseFenceCol.o"
    number 6
endseg

beginseg
    name "object_masterkokiri"
    compress
    include "$(BUILD_DIR)/assets/objects/object_masterkokiri/object_masterkokiri.o"
    number 6
endseg

beginseg
    name "object_masterkokirihead"
    compress
    include "$(BUILD_DIR)/assets/objects/object_masterkokirihead/object_masterkokirihead.o"
    number 6
endseg

beginseg
    name "object_mastergolon"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mastergolon/object_mastergolon.o"
    number 6
endseg

beginseg
    name "object_masterzoora"
    compress
    include "$(BUILD_DIR)/assets/objects/object_masterzoora/object_masterzoora.o"
    number 6
endseg

beginseg
    name "object_aob"
    compress
    include "$(BUILD_DIR)/assets/objects/object_aob/object_aob.o"
    number 6
endseg

beginseg
    name "object_ik"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ik/object_ik.o"
    include "$(BUILD_DIR)/assets/objects/object_ik/object_ik_extra.o"
    number 6
endseg

beginseg
    name "object_ahg"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ahg/object_ahg.o"
    number 6
endseg

beginseg
    name "object_cne"
    compress
    include "$(BUILD_DIR)/assets/objects/object_cne/object_cne.o"
    number 6
endseg

beginseg
    name "object_gi_niwatori"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_niwatori/object_gi_niwatori.o"
    number 6
endseg

beginseg
    name "object_skj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_skj/object_skj.o"
    number 6
endseg

beginseg
    name "object_gi_bottle_letter"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bottle_letter/object_gi_bottle_letter.o"
    number 6
endseg

beginseg
    name "object_bji"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bji/object_bji.o"
    number 6
endseg

beginseg
    name "object_bba"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bba/object_bba.o"
    number 6
endseg

beginseg
    name "object_gi_ocarina_0"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_ocarina_0/object_gi_ocarina_0.o"
    number 6
endseg

beginseg
    name "object_ds"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ds/object_ds.o"
    number 6
endseg

beginseg
    name "object_ane"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ane/object_ane.o"
    number 6
endseg

beginseg
    name "object_boj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_boj/object_boj.o"
    number 6
endseg

beginseg
    name "object_spot03_object"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot03_object/object_spot03_object.o"
    number 6
endseg

beginseg
    name "object_spot07_object"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot07_object/object_spot07_object.o"
    number 6
endseg

beginseg
    name "object_fz"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fz/object_fz.o"
    number 6
endseg

beginseg
    name "object_bob"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bob/object_bob.o"
    number 6
endseg

beginseg
    name "object_ge1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ge1/object_ge1.o"
    number 6
endseg

beginseg
    name "object_yabusame_point"
    compress
    include "$(BUILD_DIR)/assets/objects/object_yabusame_point/object_yabusame_point.o"
    number 6
endseg

beginseg
    name "object_gi_boots_2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_boots_2/object_gi_boots_2.o"
    include "$(BUILD_DIR)/assets/objects/object_gi_boots_2/object_gi_boots_2_extra.o"
    number 6
endseg

beginseg
    name "object_gi_seed"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_seed/object_gi_seed.o"
    number 6
endseg

beginseg
    name "object_gnd_magic"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gnd_magic/object_gnd_magic.o"
    number 6
endseg

beginseg
    name "object_d_elevator"
    compress
    include "$(BUILD_DIR)/assets/objects/object_d_elevator/object_d_elevator.o"
    number 6
endseg

beginseg
    name "object_d_hsblock"
    compress
    include "$(BUILD_DIR)/assets/objects/object_d_hsblock/object_d_hsblock.o"
    number 6
endseg

beginseg
    name "object_d_lift"
    compress
    include "$(BUILD_DIR)/assets/objects/object_d_lift/object_d_lift.o"
    number 6
endseg

beginseg
    name "object_mamenoki"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mamenoki/object_mamenoki.o"
    number 6
endseg

beginseg
    name "object_goroiwa"
    compress
    include "$(BUILD_DIR)/assets/objects/object_goroiwa/object_goroiwa.o"
    number 6
endseg

beginseg
    name "object_toryo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_toryo/object_toryo.o"
    number 6
endseg

beginseg
    name "object_daiku"
    compress
    include "$(BUILD_DIR)/assets/objects/object_daiku/object_daiku.o"
    number 6
endseg

beginseg
    name "object_blkobj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_blkobj/object_blkobj.o"
    number 6
endseg

beginseg
    name "object_gm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gm/object_gm.o"
    number 6
endseg

beginseg
    name "object_ms"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ms/object_ms.o"
    number 6
endseg

beginseg
    name "object_hs"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hs/object_hs.o"
    number 6
endseg

beginseg
    name "object_ingate"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ingate/object_ingate.o"
    number 6
endseg

beginseg
    name "object_lightswitch"
    compress
    include "$(BUILD_DIR)/assets/objects/object_lightswitch/object_lightswitch.o"
    number 6
endseg

beginseg
    name "object_kusa"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kusa/object_kusa.o"
    number 6
endseg

beginseg
    name "object_tsubo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_tsubo/object_tsubo.o"
    number 6
endseg

beginseg
    name "object_gi_gloves"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_gloves/object_gi_gloves.o"
    number 6
endseg

beginseg
    name "object_gi_coin"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_coin/object_gi_coin.o"
    number 6
endseg

beginseg
    name "object_kanban"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kanban/object_kanban.o"
    number 6
endseg

beginseg
    name "object_gjyo_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gjyo_objects/object_gjyo_objects.o"
    number 6
endseg

beginseg
    name "object_owl"
    compress
    include "$(BUILD_DIR)/assets/objects/object_owl/object_owl.o"
    number 6
endseg

beginseg
    name "object_mk"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mk/object_mk.o"
    number 6
endseg

beginseg
    name "object_fu"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fu/object_fu.o"
    number 6
endseg

beginseg
    name "object_gi_ki_tan_mask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_ki_tan_mask/object_gi_ki_tan_mask.o"
    number 6
endseg

beginseg
    name "object_gi_redead_mask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_redead_mask/object_gi_redead_mask.o"
    number 6
endseg

beginseg
    name "object_gi_skj_mask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_skj_mask/object_gi_skj_mask.o"
    number 6
endseg

beginseg
    name "object_gi_rabit_mask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_rabit_mask/object_gi_rabit_mask.o"
    number 6
endseg

beginseg
    name "object_gi_truth_mask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_truth_mask/object_gi_truth_mask.o"
    number 6
endseg

beginseg
    name "object_ganon_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon_objects/object_ganon_objects.o"
    number 6
endseg

beginseg
    name "object_siofuki"
    compress
    include "$(BUILD_DIR)/assets/objects/object_siofuki/object_siofuki.o"
    number 6
endseg

beginseg
    name "object_stream"
    compress
    include "$(BUILD_DIR)/assets/objects/object_stream/object_stream.o"
    number 6
endseg

beginseg
    name "object_mm"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mm/object_mm.o"
    number 6
endseg

beginseg
    name "object_fa"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fa/object_fa.o"
    number 6
endseg

beginseg
    name "object_os"
    compress
    include "$(BUILD_DIR)/assets/objects/object_os/object_os.o"
    number 6
endseg

beginseg
    name "object_gi_eye_lotion"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_eye_lotion/object_gi_eye_lotion.o"
    number 6
endseg

beginseg
    name "object_gi_powder"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_powder/object_gi_powder.o"
    number 6
endseg

beginseg
    name "object_gi_mushroom"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_mushroom/object_gi_mushroom.o"
    number 6
endseg

beginseg
    name "object_gi_ticketstone"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_ticketstone/object_gi_ticketstone.o"
    number 6
endseg

beginseg
    name "object_gi_brokensword"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_brokensword/object_gi_brokensword.o"
    number 6
endseg

beginseg
    name "object_js"
    compress
    include "$(BUILD_DIR)/assets/objects/object_js/object_js.o"
    number 6
endseg

beginseg
    name "object_cs"
    compress
    include "$(BUILD_DIR)/assets/objects/object_cs/object_cs.o"
    include "$(BUILD_DIR)/assets/objects/object_cs/object_cs_extra.o"
    number 6
endseg

beginseg
    name "object_gi_prescription"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_prescription/object_gi_prescription.o"
    number 6
endseg

beginseg
    name "object_gi_bracelet"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_bracelet/object_gi_bracelet.o"
    number 6
endseg

beginseg
    name "object_gi_soldout"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_soldout/object_gi_soldout.o"
    number 6
endseg

beginseg
    name "object_gi_frog"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_frog/object_gi_frog.o"
    number 6
endseg

beginseg
    name "object_mag"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mag/object_mag.o"
    number 6
endseg

beginseg
    name "object_door_gerudo"
    compress
    include "$(BUILD_DIR)/assets/objects/object_door_gerudo/object_door_gerudo.o"
    number 6
endseg

beginseg
    name "object_gt"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gt/object_gt.o"
    number 6
endseg

beginseg
    name "object_efc_erupc"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_erupc/object_efc_erupc.o"
    number 6
endseg

beginseg
    name "object_zl2_anime1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zl2_anime1/object_zl2_anime1.o"
    number 6
endseg

beginseg
    name "object_zl2_anime2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zl2_anime2/object_zl2_anime2.o"
    number 6
endseg

beginseg
    name "object_gi_golonmask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_golonmask/object_gi_golonmask.o"
    number 6
endseg

beginseg
    name "object_gi_zoramask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_zoramask/object_gi_zoramask.o"
    number 6
endseg

beginseg
    name "object_gi_gerudomask"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_gerudomask/object_gi_gerudomask.o"
    number 6
endseg

beginseg
    name "object_ganon2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon2/object_ganon2.o"
#if OOT_NTSC_N64
    include "$(BUILD_DIR)/assets/objects/object_ganon2/object_ganon2_title_card.o"
#endif
    number 6
endseg

beginseg
    name "object_ka"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ka/object_ka.o"
    number 6
endseg

beginseg
    name "object_ts"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ts/object_ts.o"
    number 6
endseg

beginseg
    name "object_zg"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zg/gTowerCollapseBarsDL.o"
    include "$(BUILD_DIR)/assets/objects/object_zg/gTowerCollapseBarsCol.o"
    number 6
endseg

beginseg
    name "object_gi_hoverboots"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_hoverboots/object_gi_hoverboots.o"
    number 6
endseg

beginseg
    name "object_gi_m_arrow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_m_arrow/object_gi_m_arrow.o"
    number 6
endseg

beginseg
    name "object_ds2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ds2/object_ds2.o"
    number 6
endseg

beginseg
    name "object_ec"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ec/object_ec.o"
    number 6
endseg

beginseg
    name "object_fish"
    compress
    include "$(BUILD_DIR)/assets/objects/object_fish/object_fish.o"
    number 6
endseg

beginseg
    name "object_gi_sutaru"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_sutaru/object_gi_sutaru.o"
    number 6
endseg

beginseg
    name "object_gi_goddess"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_goddess/object_gi_goddess.o"
    number 6
endseg

beginseg
    name "object_ssh"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ssh/object_ssh.o"
    number 6
endseg

beginseg
    name "object_bigokuta"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bigokuta/object_bigokuta.o"
    number 6
endseg

beginseg
    name "object_bg"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bg/object_bg.o"
    number 6
endseg

beginseg
    name "object_spot05_objects"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot05_objects/object_spot05_objects.o"
    number 6
endseg

beginseg
    name "object_spot12_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot12_obj/object_spot12_obj.o"
    number 6
endseg

beginseg
    name "object_bombiwa"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bombiwa/object_bombiwa.o"
    number 6
endseg

beginseg
    name "object_hintnuts"
    compress
    include "$(BUILD_DIR)/assets/objects/object_hintnuts/object_hintnuts.o"
    number 6
endseg

beginseg
    name "object_rs"
    compress
    include "$(BUILD_DIR)/assets/objects/object_rs/object_rs.o"
    number 6
endseg

beginseg
    name "object_spot00_break"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot00_break/object_spot00_break.o"
    number 6
endseg

beginseg
    name "object_gla"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gla/object_gla.o"
    number 6
endseg

beginseg
    name "object_shopnuts"
    compress
    include "$(BUILD_DIR)/assets/objects/object_shopnuts/object_shopnuts.o"
    number 6
endseg

beginseg
    name "object_geldb"
    compress
    include "$(BUILD_DIR)/assets/objects/object_geldb/object_geldb.o"
    number 6
endseg

beginseg
    name "object_gr"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gr/object_gr.o"
    number 6
endseg

beginseg
    name "object_dog"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dog/object_dog.o"
    number 6
endseg

beginseg
    name "object_jya_iron"
    compress
    include "$(BUILD_DIR)/assets/objects/object_jya_iron/object_jya_iron.o"
    number 6
endseg

beginseg
    name "object_jya_door"
    compress
    include "$(BUILD_DIR)/assets/objects/object_jya_door/object_jya_door.o"
    number 6
endseg

beginseg
    name "object_spot01_objects2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot01_objects2/object_spot01_objects2.o"
    number 6
endseg

beginseg
    name "object_spot11_obj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot11_obj/object_spot11_obj.o"
    number 6
endseg

beginseg
    name "object_kibako2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_kibako2/object_kibako2.o"
    number 6
endseg

beginseg
    name "object_dns"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dns/object_dns.o"
    number 6
endseg

beginseg
    name "object_dnk"
    compress
    include "$(BUILD_DIR)/assets/objects/object_dnk/object_dnk.o"
    number 6
endseg

beginseg
    name "object_gi_fire"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_fire/object_gi_fire.o"
    number 6
endseg

beginseg
    name "object_gi_insect"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_insect/object_gi_insect.o"
    number 6
endseg

beginseg
    name "object_gi_butterfly"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_butterfly/object_gi_butterfly.o"
    number 6
endseg

beginseg
    name "object_gi_ghost"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_ghost/object_gi_ghost.o"
    number 6
endseg

beginseg
    name "object_gi_soul"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_soul/object_gi_soul.o"
    number 6
endseg

beginseg
    name "object_bowl"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bowl/object_bowl.o"
    number 6
endseg

beginseg
    name "object_po_field"
    compress
    include "$(BUILD_DIR)/assets/objects/object_po_field/object_po_field.o"
    number 6
endseg

beginseg
    name "object_demo_kekkai"
    compress
    include "$(BUILD_DIR)/assets/objects/object_demo_kekkai/object_demo_kekkai.o"
    number 6
endseg

beginseg
    name "object_efc_doughnut"
    compress
    include "$(BUILD_DIR)/assets/objects/object_efc_doughnut/object_efc_doughnut.o"
    number 6
endseg

beginseg
    name "object_gi_dekupouch"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_dekupouch/object_gi_dekupouch.o"
    number 6
endseg

beginseg
    name "object_ganon_anime1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime1/object_ganon_anime1.o"
    number 6
endseg

beginseg
    name "object_ganon_anime2"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime2/object_ganon_anime2.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime2/object_ganon_anime2_extra.o"
    number 6
endseg

beginseg
    name "object_ganon_anime3"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfShowTriforceStartAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfBurstOutAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfTransformEndAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfFloatingHeavyBreathingAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfTransformStartAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfTransformLoopAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanondorfShowTriforceLoopAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanonUncurlAndFlailAnim.o"
    include "$(BUILD_DIR)/assets/objects/object_ganon_anime3/gGanonRoarAnim.o"
    number 6
endseg

beginseg
    name "object_gi_rupy"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_rupy/object_gi_rupy.o"
    number 6
endseg

beginseg
    name "object_spot01_matoya"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot01_matoya/object_spot01_matoya.o"
    number 6
endseg

beginseg
    name "object_spot01_matoyab"
    compress
    include "$(BUILD_DIR)/assets/objects/object_spot01_matoyab/object_spot01_matoyab.o"
    number 6
endseg

beginseg
    name "object_po_composer"
    compress
    include "$(BUILD_DIR)/assets/objects/object_po_composer/object_po_composer.o"
    number 6
endseg

beginseg
    name "object_mu"
    compress
    include "$(BUILD_DIR)/assets/objects/object_mu/object_mu.o"
    number 6
endseg

beginseg
    name "object_wf"
    compress
    include "$(BUILD_DIR)/assets/objects/object_wf/object_wf.o"
    number 6
endseg

beginseg
    name "object_skb"
    compress
    include "$(BUILD_DIR)/assets/objects/object_skb/object_skb.o"
    number 6
endseg

beginseg
    name "object_gj"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gj/object_gj.o"
    number 6
endseg

beginseg
    name "object_geff"
    compress
    include "$(BUILD_DIR)/assets/objects/object_geff/object_geff.o"
    number 6
endseg

beginseg
    name "object_haka_door"
    compress
    include "$(BUILD_DIR)/assets/objects/object_haka_door/object_haka_door.o"
    number 6
endseg

beginseg
    name "object_gs"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gs/object_gs.o"
    number 6
endseg

beginseg
    name "object_ps"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ps/object_ps.o"
    number 6
endseg

beginseg
    name "object_bwall"
    compress
    include "$(BUILD_DIR)/assets/objects/object_bwall/object_bwall.o"
    number 6
endseg

beginseg
    name "object_crow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_crow/object_crow.o"
    number 6
endseg

beginseg
    name "object_cow"
    compress
    include "$(BUILD_DIR)/assets/objects/object_cow/object_cow.o"
    number 6
endseg

beginseg
    name "object_cob"
    compress
    include "$(BUILD_DIR)/assets/objects/object_cob/object_cob.o"
    number 6
endseg

beginseg
    name "object_gi_sword_1"
    compress
    include "$(BUILD_DIR)/assets/objects/object_gi_sword_1/object_gi_sword_1.o"
    number 6
endseg

beginseg
    name "object_door_killer"
    compress
    include "$(BUILD_DIR)/assets/objects/object_door_killer/object_door_killer.o"
    number 6
endseg

beginseg
    name "object_ouke_haka"
    compress
    include "$(BUILD_DIR)/assets/objects/object_ouke_haka/object_ouke_haka.o"
    number 6
endseg

beginseg
    name "object_timeblock"
    compress
    include "$(BUILD_DIR)/assets/objects/object_timeblock/gSongOfTimeBlockDL.o"
    include "$(BUILD_DIR)/assets/objects/object_timeblock/gSongOfTimeBlockCol.o"
    number 6
endseg

beginseg
    name "object_zl4"
    compress
    include "$(BUILD_DIR)/assets/objects/object_zl4/object_zl4.o"
    number 6
endseg
