beginseg
    name "ydan_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_scene.o"
    number 2
endseg

beginseg
    name "ydan_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_0.o"
    number 3
endseg

beginseg
    name "ydan_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_1.o"
    number 3
endseg

beginseg
    name "ydan_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_2.o"
    number 3
endseg

beginseg
    name "ydan_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_3.o"
    number 3
endseg

beginseg
    name "ydan_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_4.o"
    number 3
endseg

beginseg
    name "ydan_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_5.o"
    number 3
endseg

beginseg
    name "ydan_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_6.o"
    number 3
endseg

beginseg
    name "ydan_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_7.o"
    number 3
endseg

beginseg
    name "ydan_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_8.o"
    number 3
endseg

beginseg
    name "ydan_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_9.o"
    number 3
endseg

beginseg
    name "ydan_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_10.o"
    number 3
endseg

beginseg
    name "ydan_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ydan/ydan_room_11.o"
    number 3
endseg

beginseg
    name "ddan_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_scene.o"
    number 2
endseg

beginseg
    name "ddan_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_0.o"
    number 3
endseg

beginseg
    name "ddan_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_1.o"
    number 3
endseg

beginseg
    name "ddan_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_2.o"
    number 3
endseg

beginseg
    name "ddan_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_3.o"
    number 3
endseg

beginseg
    name "ddan_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_4.o"
    number 3
endseg

beginseg
    name "ddan_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_5.o"
    number 3
endseg

beginseg
    name "ddan_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_6.o"
    number 3
endseg

beginseg
    name "ddan_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_7.o"
    number 3
endseg

beginseg
    name "ddan_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_8.o"
    number 3
endseg

beginseg
    name "ddan_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_9.o"
    number 3
endseg

beginseg
    name "ddan_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_10.o"
    number 3
endseg

beginseg
    name "ddan_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_11.o"
    number 3
endseg

beginseg
    name "ddan_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_12.o"
    number 3
endseg

beginseg
    name "ddan_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_13.o"
    number 3
endseg

beginseg
    name "ddan_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_14.o"
    number 3
endseg

beginseg
    name "ddan_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_15.o"
    number 3
endseg

beginseg
    name "ddan_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ddan/ddan_room_16.o"
    number 3
endseg

beginseg
    name "bdan_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_scene.o"
    number 2
endseg

beginseg
    name "bdan_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_0.o"
    number 3
endseg

beginseg
    name "bdan_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_1.o"
    number 3
endseg

beginseg
    name "bdan_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_2.o"
    number 3
endseg

beginseg
    name "bdan_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_3.o"
    number 3
endseg

beginseg
    name "bdan_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_4.o"
    number 3
endseg

beginseg
    name "bdan_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_5.o"
    number 3
endseg

beginseg
    name "bdan_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_6.o"
    number 3
endseg

beginseg
    name "bdan_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_7.o"
    number 3
endseg

beginseg
    name "bdan_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_8.o"
    number 3
endseg

beginseg
    name "bdan_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_9.o"
    number 3
endseg

beginseg
    name "bdan_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_10.o"
    number 3
endseg

beginseg
    name "bdan_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_11.o"
    number 3
endseg

beginseg
    name "bdan_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_12.o"
    number 3
endseg

beginseg
    name "bdan_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_13.o"
    number 3
endseg

beginseg
    name "bdan_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_14.o"
    number 3
endseg

beginseg
    name "bdan_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/bdan/bdan_room_15.o"
    number 3
endseg

beginseg
    name "Bmori1_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_scene.o"
    number 2
endseg

beginseg
    name "Bmori1_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_0.o"
    number 3
endseg

beginseg
    name "Bmori1_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_1.o"
    number 3
endseg

beginseg
    name "Bmori1_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_2.o"
    number 3
endseg

beginseg
    name "Bmori1_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_3.o"
    number 3
endseg

beginseg
    name "Bmori1_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_4.o"
    number 3
endseg

beginseg
    name "Bmori1_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_5.o"
    number 3
endseg

beginseg
    name "Bmori1_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_6.o"
    number 3
endseg

beginseg
    name "Bmori1_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_7.o"
    number 3
endseg

beginseg
    name "Bmori1_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_8.o"
    number 3
endseg

beginseg
    name "Bmori1_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_9.o"
    number 3
endseg

beginseg
    name "Bmori1_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_10.o"
    number 3
endseg

beginseg
    name "Bmori1_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_11.o"
    number 3
endseg

beginseg
    name "Bmori1_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_12.o"
    number 3
endseg

beginseg
    name "Bmori1_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_13.o"
    number 3
endseg

beginseg
    name "Bmori1_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_14.o"
    number 3
endseg

beginseg
    name "Bmori1_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_15.o"
    number 3
endseg

beginseg
    name "Bmori1_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_16.o"
    number 3
endseg

beginseg
    name "Bmori1_room_17"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_17.o"
    number 3
endseg

beginseg
    name "Bmori1_room_18"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_18.o"
    number 3
endseg

beginseg
    name "Bmori1_room_19"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_19.o"
    number 3
endseg

beginseg
    name "Bmori1_room_20"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_20.o"
    number 3
endseg

beginseg
    name "Bmori1_room_21"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_21.o"
    number 3
endseg

beginseg
    name "Bmori1_room_22"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/Bmori1/Bmori1_room_22.o"
    number 3
endseg

beginseg
    name "HIDAN_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_scene.o"
    number 2
endseg

beginseg
    name "HIDAN_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_0.o"
    number 3
endseg

beginseg
    name "HIDAN_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_1.o"
    number 3
endseg

beginseg
    name "HIDAN_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_2.o"
    number 3
endseg

beginseg
    name "HIDAN_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_3.o"
    number 3
endseg

beginseg
    name "HIDAN_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_4.o"
    number 3
endseg

beginseg
    name "HIDAN_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_5.o"
    number 3
endseg

beginseg
    name "HIDAN_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_6.o"
    number 3
endseg

beginseg
    name "HIDAN_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_7.o"
    number 3
endseg

beginseg
    name "HIDAN_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_8.o"
    number 3
endseg

beginseg
    name "HIDAN_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_9.o"
    number 3
endseg

beginseg
    name "HIDAN_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_10.o"
    number 3
endseg

beginseg
    name "HIDAN_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_11.o"
    number 3
endseg

beginseg
    name "HIDAN_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_12.o"
    number 3
endseg

beginseg
    name "HIDAN_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_13.o"
    number 3
endseg

beginseg
    name "HIDAN_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_14.o"
    number 3
endseg

beginseg
    name "HIDAN_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_15.o"
    number 3
endseg

beginseg
    name "HIDAN_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_16.o"
    number 3
endseg

beginseg
    name "HIDAN_room_17"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_17.o"
    number 3
endseg

beginseg
    name "HIDAN_room_18"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_18.o"
    number 3
endseg

beginseg
    name "HIDAN_room_19"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_19.o"
    number 3
endseg

beginseg
    name "HIDAN_room_20"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_20.o"
    number 3
endseg

beginseg
    name "HIDAN_room_21"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_21.o"
    number 3
endseg

beginseg
    name "HIDAN_room_22"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_22.o"
    number 3
endseg

beginseg
    name "HIDAN_room_23"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_23.o"
    number 3
endseg

beginseg
    name "HIDAN_room_24"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_24.o"
    number 3
endseg

beginseg
    name "HIDAN_room_25"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_25.o"
    number 3
endseg

beginseg
    name "HIDAN_room_26"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HIDAN/HIDAN_room_26.o"
    number 3
endseg

beginseg
    name "MIZUsin_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_scene.o"
    number 2
endseg

beginseg
    name "MIZUsin_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_0.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_1.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_2.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_3.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_4.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_5.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_6.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_7.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_8.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_9.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_10.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_11.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_12.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_13.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_14.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_15.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_16.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_17"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_17.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_18"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_18.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_19"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_19.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_20"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_20.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_21"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_21.o"
    number 3
endseg

beginseg
    name "MIZUsin_room_22"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/MIZUsin/MIZUsin_room_22.o"
    number 3
endseg

beginseg
    name "jyasinzou_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_scene.o"
    number 2
endseg

beginseg
    name "jyasinzou_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_0.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_1.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_2.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_3.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_4.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_5.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_6.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_7.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_8.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_9.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_10.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_11.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_12.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_13.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_14.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_15.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_16.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_17"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_17.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_18"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_18.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_19"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_19.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_20"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_20.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_21"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_21.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_22"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_22.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_23"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_23.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_24"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_24.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_25"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_25.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_26"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_26.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_27"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_27.o"
    number 3
endseg

beginseg
    name "jyasinzou_room_28"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/jyasinzou/jyasinzou_room_28.o"
    number 3
endseg

beginseg
    name "HAKAdan_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_scene.o"
    number 2
endseg

beginseg
    name "HAKAdan_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_0.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_1.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_2.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_3.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_4.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_5.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_6.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_7.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_8.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_9.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_10.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_11.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_12.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_13.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_14.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_15.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_16.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_17"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_17.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_18"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_18.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_19"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_19.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_20"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_20.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_21"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_21.o"
    number 3
endseg

beginseg
    name "HAKAdan_room_22"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdan/HAKAdan_room_22.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_scene.o"
    number 2
endseg

beginseg
    name "HAKAdanCH_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_0.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_1.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_2.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_3.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_4.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_5.o"
    number 3
endseg

beginseg
    name "HAKAdanCH_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/HAKAdanCH/HAKAdanCH_room_6.o"
    number 3
endseg

beginseg
    name "ice_doukutu_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_scene.o"
    number 2
endseg

beginseg
    name "ice_doukutu_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_0.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_1.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_2.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_3.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_4.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_5.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_6.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_7.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_8.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_9.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_10.o"
    number 3
endseg

beginseg
    name "ice_doukutu_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ice_doukutu/ice_doukutu_room_11.o"
    number 3
endseg

beginseg
    name "men_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_scene.o"
    number 2
endseg

beginseg
    name "men_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_0.o"
    number 3
endseg

beginseg
    name "men_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_1.o"
    number 3
endseg

beginseg
    name "men_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_2.o"
    number 3
endseg

beginseg
    name "men_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_3.o"
    number 3
endseg

beginseg
    name "men_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_4.o"
    number 3
endseg

beginseg
    name "men_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_5.o"
    number 3
endseg

beginseg
    name "men_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_6.o"
    number 3
endseg

beginseg
    name "men_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_7.o"
    number 3
endseg

beginseg
    name "men_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_8.o"
    number 3
endseg

beginseg
    name "men_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_9.o"
    number 3
endseg

beginseg
    name "men_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/men/men_room_10.o"
    number 3
endseg

beginseg
    name "ganontika_scene"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_scene.o"
    number 2
endseg

beginseg
    name "ganontika_room_0"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_0.o"
    number 3
endseg

beginseg
    name "ganontika_room_1"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_1.o"
    number 3
endseg

beginseg
    name "ganontika_room_2"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_2.o"
    number 3
endseg

beginseg
    name "ganontika_room_3"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_3.o"
    number 3
endseg

beginseg
    name "ganontika_room_4"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_4.o"
    number 3
endseg

beginseg
    name "ganontika_room_5"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_5.o"
    number 3
endseg

beginseg
    name "ganontika_room_6"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_6.o"
    number 3
endseg

beginseg
    name "ganontika_room_7"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_7.o"
    number 3
endseg

beginseg
    name "ganontika_room_8"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_8.o"
    number 3
endseg

beginseg
    name "ganontika_room_9"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_9.o"
    number 3
endseg

beginseg
    name "ganontika_room_10"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_10.o"
    number 3
endseg

beginseg
    name "ganontika_room_11"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_11.o"
    number 3
endseg

beginseg
    name "ganontika_room_12"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_12.o"
    number 3
endseg

beginseg
    name "ganontika_room_13"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_13.o"
    number 3
endseg

beginseg
    name "ganontika_room_14"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_14.o"
    number 3
endseg

beginseg
    name "ganontika_room_15"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_15.o"
    number 3
endseg

beginseg
    name "ganontika_room_16"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_16.o"
    number 3
endseg

beginseg
    name "ganontika_room_17"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_17.o"
    number 3
endseg

beginseg
    name "ganontika_room_18"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_18.o"
    number 3
endseg

beginseg
    name "ganontika_room_19"
    compress
    include "$(BUILD_DIR)/assets/scenes/dungeons_mq/ganontika/ganontika_room_19.o"
    number 3
endseg
