    SCENE_CMD_ECHO_SETTINGS(7),
    SCENE_CMD_ROOM_BEHAVIOR(ROOM_TYPE_DUNGEON, ROOM_ENV_DEFAULT, LENS_MODE_SHOW_ACTORS, false /* warp songs enabled */),
    SCENE_CMD_SKYBOX_DISABLES(true /* no skybox */, true /* no sun/moon */),
    SCENE_CMD_TIME_SETTINGS(/* don't set time */ 0xFF, 0xFF, 0 /* time doesn't move */),
    SCENE_CMD_ROOM_SHAPE(&MIZUsin_room_8_030000F0_RoomShapeCullable),
    SCENE_CMD_OBJECT_LIST(ARRAY_COUNT(cq_objects), cq_objects),
    SCENE_CMD_ACTOR_LIST(ARRAY_COUNT(cq_actors), cq_actors),
    SCENE_CMD_END(),
