    OBJECT_BDAN_OBJECTS, // 0
    OBJECT_BOX, // 1
    OBJECT_EI, // 2
    OBJECT_ZF, // 3
    OBJECT_TIMEBLOCK, // 4
    OBJECT_EFC_TW, // 5
    OBJECT_KUSA, // 6
    OBJECT_RR, // 7
    OBJECT_GI_SHIELD_1, // 8
    OBJECT_GI_SHIELD_2, // 9
    OBJECT_GI_SUTARU, // 10
    OBJECT_ST, // 11
    OBJECT_EFC_FLASH, // 12
    OBJECT_MIZU_OBJECTS, // 13
    OBJECT_SIOFUKI, // 14

