    OBJECT_BDAN_OBJECTS, // 0
    OBJECT_RU1, // 1
    OBJECT_TIMEBLOCK, // 2
    OBJECT_EFC_TW, // 3
    OBJECT_SIOFUKI, // 4
    OBJECT_KUSA, // 5
    OBJECT_ST, // 6
    OBJECT_GI_SUTARU, // 7
    OBJECT_BOMBIWA, // 8
    OBJECT_TP, // 9
    OBJECT_BUBBLE, // 10

