    OBJECT_HAKA_OBJECTS, // 0
    OBJECT_HAKA_DOOR, // 1
    OBJECT_BOX, // 2
    OBJECT_SYOKUDAI, // 3
    OBJECT_HAKACH_OBJECTS, // 4
    OBJECT_RD, // 5
    OBJECT_ST, // 6
    OBJECT_GI_SUTARU, // 7

