    OBJECT_HAKA_OBJECTS, // 0
    OBJECT_HAKA_DOOR, // 1
    OBJECT_BOX, // 2
    OBJECT_SYOKUDAI, // 3
    OBJECT_VM, // 4
    OBJECT_TRAP, // 5
    OBJECT_BB, // 6
    OBJECT_KANBAN, // 7
    OBJECT_D_HSBLOCK, // 8
    OBJECT_DEMO_KEKKAI, // 9
    OBJECT_BOMBF, // 10

