    SCENE_CMD_SOUND_SETTINGS(6, NATURE_ID_NONE, NA_BGM_GANON_TOWER),
    SCENE_CMD_ROOM_LIST(ARRAY_COUNT(ganon_boss_scene_02000080_RoomList), ganon_boss_scene_02000080_RoomList),
    SCENE_CMD_TRANSITION_ACTOR_LIST(ARRAY_COUNT(ganon_boss_scene_02000070_TransitionActorEntryList), ganon_boss_scene_02000070_TransitionActorEntryList),
    SCENE_CMD_MISC_SETTINGS(SCENE_CAM_TYPE_DEFAULT, 21),
    SCENE_CMD_COL_HEADER(&cq_collision),
    SCENE_CMD_ENTRANCE_LIST(ganon_boss_scene_02000088_SpawnList),
    SCENE_CMD_SPECIAL_FILES(NAVI_QUEST_HINTS_DUNGEON, OBJECT_INVALID),
    SCENE_CMD_SPAWN_LIST(ARRAY_COUNT(ganon_boss_scene_02000060_PlayerEntryList), ganon_boss_scene_02000060_PlayerEntryList),
    SCENE_CMD_SKYBOX_SETTINGS(SKYBOX_UNSET_1D, 0, LIGHT_MODE_TIME),
    SCENE_CMD_EXIT_LIST(ganon_boss_scene_0200008C_ExitList),
    SCENE_CMD_ENV_LIGHT_SETTINGS(ARRAY_COUNT(ganon_boss_scene_02000090_EnvLightSettingsList), ganon_boss_scene_02000090_EnvLightSettingsList),
    SCENE_CMD_END(),
