    OBJECT_MORI_TEX, // 0
    OBJECT_MORI_OBJECTS, // 1
    OBJECT_BOX, // 2
    OBJECT_SYOKUDAI, // 3
    OBJECT_BB, // 4
    OBJECT_ST, // 5
    OBJECT_DEMO_KEKKAI, // 6
    OBJECT_YDAN_OBJECTS, // 7
    OBJECT_DEKUBABA, // 8
    OBJECT_OKUTA, // 9
    OBJECT_GI_HEART, // 10
    OBJECT_GI_SUTARU, // 11

