    OBJECT_DEMO_KEKKAI, // 0
    OBJECT_LIGHTSWITCH, // 1
    OBJECT_MIR_RAY, // 2
    OBJECT_BOX, // 3
    OBJECT_EFC_FLASH, // 4
    OBJECT_SYOKUDAI, // 5
    OBJECT_BOMBIWA, // 6
    OBJECT_WALLMASTER, // 7
    OBJECT_BOX, // 8
    OBJECT_EFC_FLASH, // 9
    OBJECT_RD, // 10
    OBJECT_BB, // 11

