    OBJECT_BDAN_OBJECTS, // 0
    OBJECT_RU1, // 1
    OBJECT_OKUTA, // 2
    OBJECT_BUBBLE, // 3
    OBJECT_BL, // 4
    OBJECT_VALI, // 5
    OBJECT_EI, // 6
    OBJECT_GI_HEARTS, // 7
    OBJECT_GI_HEART, // 8
    OBJECT_SHOPNUTS, // 9

