    OBJECT_DEMO_KEKKAI, // 0
    OBJECT_LIGHTSWITCH, // 1
    OBJECT_BW, // 2
    OBJECT_MIR_RAY, // 3
    OBJECT_WALLMASTER, // 4
    OBJECT_TRAP, // 5
    OBJECT_BOX, // 6
    OBJECT_EFC_FLASH, // 7
    OBJECT_SYOKUDAI, // 8

