    OBJECT_DEMO_KEKKAI, // 0
    OBJECT_ICE_OBJECTS, // 1
    OBJECT_FZ, // 2
    OBJECT_BB, // 3
    OBJECT_FIREFLY, // 4
    OBJECT_WALLMASTER, // 5
    OBJECT_GOROIWA, // 6
    OBJECT_D_HSBLOCK, // 7

