[preserve_macros]
"g[DS]P.*" = "void"
"gDma.*" = "void"
"G_IM_SIZ_.*" = "int"
"G_[AC]C.*" = "int"
PRIMITIVE = "int"
TEXEL0 = "int"
TEXEL1 = "int"

LOG = "void"
SET_FULLSCREEN_VIEWPORT = "void"
OPEN_DISPS = "void"
CLOSE_DISPS = "void"
ABS = "int"
SQ = "int"
CLAMP = "int"
