    OBJECT_YDAN_OBJECTS, // 0
    OBJECT_GOL, // 1
    OBJECT_ST, // 2
    OBJECT_DEKUBABA, // 3
    OBJECT_DEKUNUTS, // 4
    OBJECT_BOX, // 5
    OBJECT_SYOKUDAI, // 6
    OBJECT_KUSA, // 7
    OBJECT_GI_HEART, // 8
    OBJECT_GI_SUTARU, // 9
    OBJECT_D_LIFT, // 10
    OBJECT_BOMBIWA, // 11
    OBJECT_TIMEBLOCK, // 12
    OBJECT_EFC_TW, // 13

