    OBJECT_SPOT00_BREAK, // 0
    OBJECT_WOOD02, // 1
    OBJECT_KANBAN, // 2
    OBJECT_PO_FIELD, // 3
    OBJECT_HORSE, // 4
    OBJECT_BOMBIWA, // 5
    OBJECT_MM, // 6
    OBJECT_SPOT00_OBJECTS, // 7
